### ISSUE TITLE
Support OperatorMono-Book

### ISSUE THREAD

**Issue by marsqing** [kiliman/operator-mono-lig#1]
Great work! Meduim is too wide for me. Any plan to support OperatorMono-Book? Thanks!

**Comment by kiliman** [comment]
Thanks for checking out the project. I hope the instructions were clear.

Creating the actual ligatures wasn't too difficult, once I figured out how to use FontForge. The hardest part was figuring out how to extract and merge the ligatures themselves, since I can't distribute the actual font files.

Now that I've got that process down, I can work on creating ligatures for the other weights.

**Comment by marsqing** [comment]
Yes, the instructions are very clear. I have successfully created OperatorMono-Medium.😀

**Comment by bjornhanson** [comment]
Same here. The medium size is too thick for me. I might look into this eventually if you don't, but for now might try Fira Code.

**Comment by mcarter101** [comment]
I have started the ligatures for Operator Mono Book, as well as the ScreenSmart (SSm) versions. I hope to have these out by early next week.

**Comment by kiliman** [comment]
I have started the ligatures for Operator Mono Book, as well as the ScreenSmart (SSm) versions. I hope to have these out by early next week.

**Comment by kiliman** [comment]
I switched to an app call Glyphs on the Mac. It seems to be much easier to use than FontForge. Here's a screenshot of me working on the ligatures.
<img width="1055" alt="screen shot 2017-08-26 at 3 09 13 pm" src="https://user-images.githubusercontent.com/47168/29744327-d46290ea-8a70-11e7-863d-5d26e407f414.png">

**Comment by kevinsperrine** [comment]
@kiliman I'd be willing to help add/create some of these others font weights, too, but I could not figure out how to export them into XML files needed. What am I missing?

**Comment by kennyklee** [comment]
@kiliman I made manual changes to 'Book' font weight.  It worked beautifully for me.
https://github.com/kennyklee/operator-mono-book-lig

All, this forked project worked great for me.  All credit belongs to @kiliman.

**Comment by kiliman** [comment]
Sorry for the delay in getting the updated font weights. Work has been pretty hectic the past few weeks.

Also, one of the challenges is that when FontForge/Glyphs generate the actual outlines, they try to optimize by grouping similar instructions into [subroutines](https://www.microsoft.com/typography/otspec/cff2charstr.htm#section4.4). Normally this would be fine, but since I'm patching the existing font files with the new ligature outlines, the subroutine indices from the ligatures don't match (or don't exist) in the original font. 

I was able to get away with it somewhat in the original version by tweaking the outlines a bit until I had no common entries. Needless to say this was pretty time consuming. Also Glyphs seems to be much more aggressive in finding common segments, so it was getting next to impossible to eliminate all callsubr/callgsubr entries, especially with hinting.

Therefore, I had to update the patching routine to re-write and re-index the subroutines as well. This also includes subroutines that call other subroutines. Yuck!

Anyway, hope to finish up these fonts over the next couple of days. Thanks for your patience.

**Comment by kiliman** [comment]
@kennyklee Awesome. Glad you were able to figure out how things are organized. I'll actually have true Book weight ligatures shortly, so they won't look out of place with the rest of the font.

**Comment by duranivan** [comment]
@kiliman Thanks for the great work! Looking forward to the Book weight. Any chance you could add the Light weight as well any time in the future?

**Comment by kiliman** [comment]
We're getting close!

<img width="1003" alt="screen shot 2017-09-13 at 2 37 57 pm" src="https://user-images.githubusercontent.com/47168/30394730-f26d472c-9891-11e7-9151-16483db3b12c.png">

**Comment by kiliman** [comment]
I have completed the following weights:

## ScreenSmart version
* Operator Mono ScreenSmart Book
* Operator Mono ScreenSmart Book Italic
* Operator Mono ScreenSmart Medium
* *Coming Soon* Operator Mono ScreenSmart Medium Italic

## Regular version
* Operator Mono Medium
* Operator Mono Medium Italic

I've streamlined the process for generating the ligatures so I should be able to get the rest of the font weights completed this weekend. Thanks for your patience.

**Comment by kiliman** [comment]
There appears to be a slight issue with the font name tables, however they do install.

I'll take a look at it in the morning.

**Comment by kiliman** [comment]
Ugh. Hold off on installing this version. Something isn't right. I'll take a look in the morning.

**Comment by kiliman** [comment]
Making some progress this morning.

Looks like the ligatures with 3 components are not working. I'm wondering if ordering is important. Also, none of the italic ligatures are working from some reason 😢 

Anyway, here's a screenshot for the Book weight. It actually looks really nice.

![image](https://user-images.githubusercontent.com/47168/30512287-ebcde9f6-9ab9-11e7-8b26-124a410e1719.png)

**Comment by kiliman** [comment]
Apparently order does matter! Now to figure out what's wrong with the italics.

![image](https://user-images.githubusercontent.com/47168/30512339-37c13132-9abb-11e7-9f85-9e4f0d818b61.png)

**Comment by kiliman** [comment]
In my Glyphs version of the font, the italic ligatures (except for the html comment start) are working, so must be an issue with the extraction/build.

![image](https://user-images.githubusercontent.com/47168/30512370-02e1fea0-9abc-11e7-8021-e6ed6808a3f3.png)

**Comment by kiliman** [comment]
Ok, I've fixed the issues with Windows, however still can't get italics to work.

I'm going to close this issue and create a new issue for italics.

Please try this out and let me know if you have any problems.

Thanks!

**Comment by iStefo** [comment]
Not sure whether this belongs into this issue, but this is what happened when I built the ScreenSmart versions and installed them on macOS 10.12.6, the glyphs seem to lose their correct width:
 
<img width="512" alt="screen shot 2017-09-18 at 22 43 11" src="https://user-images.githubusercontent.com/768764/30563742-1b93847e-9cc3-11e7-9ebf-57d47534df31.png">

Loading them into the http://www.glyphrstudio.com/online/ tool shows the same problem:

![screen shot 2017-09-18 at 22 44 39](https://user-images.githubusercontent.com/768764/30563765-2f059e66-9cc3-11e7-89e6-969924bad1db.png)

Checking the "auto calculate" checkbox changes the right border:

![screen shot 2017-09-18 at 22 44 42](https://user-images.githubusercontent.com/768764/30563768-313b6c7e-9cc3-11e7-9828-790ba4faf994.png)

Which has an effect when loading the resulting front in the system's font program:

<img width="512" alt="screen shot 2017-09-18 at 22 43 15" src="https://user-images.githubusercontent.com/768764/30563797-542739a2-9cc3-11e7-9172-18ce965bf7bc.png">

Without the correct glyph width, the result looks like this:

![screen shot 2017-09-18 at 22 49 01](https://user-images.githubusercontent.com/768764/30563914-9f39cb8a-9cc3-11e7-94ee-ee031850bdeb.png)

I have attempted to fix the problem myself but can't find out where in the process the glyph width gets lost :(

Debugging info: I am using node v8.2.1, python 2.7 and fonttools 3.15.1.

**Comment by kiliman** [comment]
@iStefo Thanks for the detailed bug report. Can you pull latest and rebuild the fonts?

I'm not seeing what you're seeing. Just remember, for the ScreenSmart versions, I only have Book/Book Italic and Medium (no italic yet).

As you can see from the screenshots (Operator Mono SSm Lig Medium), VS Code is synthesizing italics (you get the slanted ligatures, but also slanted character, not true italics). 

If you're still having problems, can you create a new issue?

Thanks!!

![image](https://user-images.githubusercontent.com/47168/30566641-d85259b0-9c9a-11e7-8499-623d043d01d0.png)
