### ISSUE TITLE
Missing Ligatures Operator Mono SSm Light

### ISSUE THREAD

**Issue by hhquerybuilder** [kiliman/operator-mono-lig#101]
I think there are some ligatures that are missing from the Light variant

Operator Mono SSm Book
<img width="454" alt="Screenshot 2019-08-07 at 11 30 27" src="https://user-images.githubusercontent.com/40240395/62607530-e9810580-b906-11e9-8997-101b05fbb4ce.png">

Operator Mono SSm Light
<img width="460" alt="Screenshot 2019-08-07 at 11 29 54" src="https://user-images.githubusercontent.com/40240395/62607564-f6055e00-b906-11e9-9a4d-f2b7fbbb4ca3.png">

**Comment by markypython** [comment]
@hhquerybuilder I compiled a full list of missing ligatures and opened an issue to track their inclusion.

See #102

**Comment by kiliman** [comment]
Fixed in v2.2.4
