### ISSUE TITLE
Add missing glyphs

### ISSUE THREAD

**Issue by markypython** [kiliman/operator-mono-lig#102]
The following glyphs are missing.

**Operator Mono Light**
- [ ] ~~percent.alt~~

**Operator Mono Light**
- [ ] ~~percent.alt~~

**Operator Mono SSm Light**
- [x] equal_equal_greater.liga
- [x] equal_equal.liga
- [x] equal_greater.liga
- [x] equal_less_less.liga
- [x] exclam_equal.liga
- [x] greater_equal_greater.liga
- [x] greater_greater_equal.liga
- [x] hyphen_greater.liga
- [x] hyphen_hyphen_greater.liga
- [x] less_equal_equal.liga
- [x] less_equal_greater.liga
- [x] less_equal_less.liga
- [x] less_hyphen_hyphen.liga
- [x] less_hyphen.liga
- [ ] ~~percent.alt~~

**Operator Mono SSm Light Italic**
- [x] equal_less_less.liga
- [x] greater_greater_equal.liga
- [ ] ~~percent.alt~~

**Comment by markypython** [comment]
Checked items fixed by #103

**Comment by kiliman** [comment]
The Light versions don't have percent.alt since the original percent already had open circles. Apparently the light was too light to have the filled circles.
