### ISSUE TITLE
Don't generate files on build folder

### ISSUE THREAD

**Issue by PedroFumero** [kiliman/operator-mono-lig#105]
I follow all the instructions on .md file, all good but when I shoot the `build` command on terminal nothing happens

![Sin título](https://user-images.githubusercontent.com/5423146/63211660-509d7780-c0c8-11e9-8d78-0a5db1188d2b.jpg)

**Comment by kiliman** [comment]
It looks like the build script did not find any fonts in the `./original` folder. Can you send me a screenshot of that folder?

**Comment by PedroFumero** [comment]
> It looks like the build script did not find any fonts in the `./original` folder. Can you send me a screenshot of that folder?

Capture added

**Comment by kiliman** [comment]
There should be a hyphen between OperatorMono and the weights. Like OperatorMono-Book.otf.

Note: this version currently only supports the Light weight for the non-ScreenSmart versions.

**Comment by PedroFumero** [comment]
Wow! Fixed with 

> hyphen between OperatorMono and the weights

Thanks a lot it looks like really cool!

![image](https://user-images.githubusercontent.com/5423146/63211963-6b71eb00-c0cc-11e9-9fc1-fbdb62c1f506.png)
