### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by drod3763** [kiliman/operator-mono-lig#107]
Wasn't sure where to place this but I made an executable Docker image for this project. Feel free to use it or link to it if you like.

https://github.com/drod3763/kiliman-operator-mono-lig-docker

**Comment by kiliman** [comment]
Nice. If you want to update the README under the Install section, I'll merge it in.

Thanks!

**Comment by kiliman** [comment]
Thanks again. I merged your update and added you to the all-contributors section.
