### ISSUE TITLE
Question: Support for non SSm versions

### ISSUE THREAD

**Issue by LuRsT** [kiliman/operator-mono-lig#110]
Just found this project yesterday (AMAZING, LOVE IT :heart: ) and after successfully patching my font, I realised that mine aren't SSm version, and that the ligatures in this project for non-SSm version are only the light ones :(. 

Am I doing something wrong? If not, is the support for non-SSm coming soon? I saw the poll and I know I'm a minority, but I'd love to have to buy yet another font.

**Comment by kiliman** [comment]
@LuRsT Hi, yes. The only non-SSm version is the Light weight for now. Which one are you using?

It takes a couple of hours to add the ligatures to a given font, and I've been pretty busy lately. That's why I've asked for help.

Anyway, let me know and I'll see if I can squeeze in some time.

**Comment by markypython** [comment]
@kiliman I've also been busy lately, but I could help out with adding some of the necessary ligs.  Let me know if you would like the help.

**Comment by LuRsT** [comment]
@kiliman @markypython Thanks for the speedy reply, I'm excited that they are in the roadmap. I'd be glad to help if I knew what it entailed to create the ligatures needed for the other font weights.

As for the one I use, I like to use `Book`

**Comment by MacZel** [comment]
:pray:

**Comment by kiliman** [comment]
@markypython Were you planning on working on Operator Mono Book? If not, I'll take care of it this weekend.

**Comment by markypython** [comment]
@kiliman I'm on vacation right now and won't be back till next week.  If you have time this weekend to work on the font that's fine.  I just wanted to offer in case you didn't have time.

**Comment by LuRsT** [comment]
@kiliman, let me know if I can help with anything at all

**Comment by kiliman** [comment]
Finally added Operator Mono Book/Book Italic ligatures. Enjoy!

Fixed in 4e50610989c51453cd57297cba153b855a34f8af
