### ISSUE TITLE
Hyphen ligatures create overlap with other caracters

### ISSUE THREAD

**Issue by KhroyaenSkrafhar** [kiliman/operator-mono-lig#111]
**Expected behavious** : monospace font, standard spacing and character width. No overlap

**What I get :**
![image](https://user-images.githubusercontent.com/16322680/65695611-200e0d80-e078-11e9-903a-c38e42544f04.png)
As you can see, the `"` caracter overlap with the `0` (it is a double-quote).

I have done some testing, this happens with double hyphen -- and simple arrow ->.
Writing several arrows or double hyphen in a row, separated by spaces, will eventually provoque overlap of entire words :
![image](https://user-images.githubusercontent.com/16322680/65695918-acb8cb80-e078-11e9-94ef-b33bf0719e9b.png)

This will not happen in every code context... String litterals produce this effect all the time, I've seen it inside braces. I don't know if there's somewhere else it can happen.

I use vscode on linux.

**Comment by kiliman** [comment]
Have you tried this with Fira Code?

Also which font weight are you using? ScreenSmart or regular?

**Comment by kufii** [comment]
I'm getting this issue too using the non-ssm version on windows

**Comment by kiliman** [comment]
Windows 10. 


ScreenSmart
![image](https://user-images.githubusercontent.com/47168/65700282-61d58e80-e04d-11e9-8f9f-6b1117408415.png)

Non-ScreenSmart
![image](https://user-images.githubusercontent.com/47168/65700310-73b73180-e04d-11e9-9683-460745800af7.png)

Not sure if it's a context thing.

Can one of you paste the actual text that is having the issue (also, let me know what language that VS Code is using (lower right).

![image](https://user-images.githubusercontent.com/47168/65700439-b416af80-e04d-11e9-930d-6a6ec5bc69ac.png)

**Comment by kufii** [comment]
I have the exact same settings as the 2nd one. Interestingly when the text is highlighted it displays correctly. language is JavaScript snippet that messes up `let x = '--> --> --> -->'`

**Comment by KhroyaenSkrafhar** [comment]
![image](https://user-images.githubusercontent.com/16322680/65700956-d1b13c80-e080-11e9-93d9-272cdd2e1102.png)
This is PHP

```
fontFamily : operator mono ssm lig book
fontLigatures: true
fontSize: 16
fontWeight: 300
```
If I am not specifying ssm, in the font family, vscode doesn't find it and fallback to default font.

**Comment by kufii** [comment]
ok, found out that with `editor.renderWhitespace: 'all'` it displays correctly

**Comment by kiliman** [comment]
That is super weird. It's working fine for me. Have you rebuilt the fonts using the latest version?

I even tested with `editor.renderWhitespace: 'none'`
![image](https://user-images.githubusercontent.com/47168/65701494-60a56100-e04f-11e9-9261-80a01a6d36c6.png)

Send me your email address to kiliman@gmail.com so we can troubleshoot.

**Comment by KhroyaenSkrafhar** [comment]
![image](https://user-images.githubusercontent.com/16322680/65701574-d62a2500-e081-11e9-82b0-5acc30086405.png)
@kufii not working with your fix

**Comment by kufii** [comment]
I'll try rebuilding my font and getting back to you

**Comment by KhroyaenSkrafhar** [comment]
Me too, It's possible I messed up something

**Comment by kufii** [comment]
ok yeah rebuilding fixed things, don't know why that happened the first time

**Comment by KhroyaenSkrafhar** [comment]
So I rebuilt everything from a clean version, which does not have SSm files, and it produced the Light and Light Italic versions only, but they work as expected. I suppose I had renamed files as SSm for some reason.

**Comment by kiliman** [comment]
If you originally built the v1.0 fonts, those included Operator Mono Book in the `./build` folder. Unfortunately v2.0 doesn't include Book, just Light. The build process didn't clean out the `./build` folder so the Book font was still there from the old build. I can see how you could have been confused.

I'll try and get the Book version done this weekend. Thanks for your patience and troubleshooting this issue.

**Comment by mcarter101** [comment]
I've added Operator Mono Book in v2.2.5. Check it out and let me know if you still have any issues.

**Comment by kiliman** [comment]
I've added Operator Mono Book in v2.2.5. Check it out and let me know if you have any issues.

**Comment by MrGabigoo** [comment]
@kiliman I was having the same issue and your update fixed it ! Thank you !

**Comment by KhroyaenSkrafhar** [comment]
It works like a charm. Thank you !
