### ISSUE TITLE
Erro na criação no Windows 10 1903

### ISSUE THREAD

**Issue by marcelloinfoweb** [kiliman/operator-mono-lig#112]
Estou tentando gerar as fontes no windows 10 1903, não faz nada quando digito o comando "build" no terminal.

Não teria como disponibilizar as fontes geradas?

**Comment by kiliman** [comment]
Desculpe pelo meu pobre português. Eu estou usando o Google Tradutor.

Você certificou-se de copiar as fontes para a pasta `./original`? Se sim, quais são os nomes das fontes? A construção requer uma convenção de nomenclatura específica.

>Sorry for my poor Portuguese. I'm using Google Translate.

>Did you make sure to copy the fonts to the `./original` folder? If so, what are the font names? The build requires a specific naming convention.

**Comment by marcelloinfoweb** [comment]
Tudo bem, deu pra entender claramente.

Sim, copiei as fontes da pasta "ligature" para a pasta "original".
Os nomes das fontes não alterei, mantive os mesmos, não encontrei um passo a passo detalhada.
Fiz o procedimento no Windows e no Linux, ambos deu na mesma, não faz nada, instalei a "tool fonts", python3, exatamente tudo, mas infelizmente não vai.

Por favor me ajude!!!

> Alright, I understood perfectly..
>
> Yes, I copied the fonts from the "ligature" folder to the "original" folder.
> The font names have not changed, I have kept them, I have not found a detailed walkthrough.
> I did the procedure on Windows and Linux, both gave the same, does nothing, installed the "tool fonts", python3, exactly everything, but unfortunately will not.
> 
>
>Please help me!!!

**Comment by kiliman** [comment]
Ok, you should copy your Operator Mono fonts (the ones WITHOUT ligatures) to the `./original` folder. Like this:

![image](https://user-images.githubusercontent.com/47168/66125682-a1ecc200-e5b5-11e9-821a-916cc3a1138b.png)

After you type `./build.sh`, you should see it output something like this:

![image](https://user-images.githubusercontent.com/47168/66125866-0ad43a00-e5b6-11e9-99cf-4405cb651c7c.png)

Then in your `./build` folder it should look like this:

![image](https://user-images.githubusercontent.com/47168/66125922-2ccdbc80-e5b6-11e9-9c3b-8de574e0fddb.png)

The `./build` folder will only contain generated fonts for the ones you have in your `./original` folder. Right now, that includes all the ScreenSmart fonts as well as the normal Book and Light fonts. NOTE: You must have the same filenames as I show in the listing above.

If you're still having issues, you might consider using the Docker instructions in the README file. That includes all of the tooling necessary to make it work.

Good luck!

**Comment by marcelloinfoweb** [comment]
Now I understand everything, is that there was not exactly this information in README, you could include there, so it was very understandable.
Thank you so much, I will try!
