### ISSUE TITLE
Are slashes supposed to look like this in HTML?

### ISSUE THREAD

**Issue by CWSpear** [kiliman/operator-mono-lig#113]
I just want to make sure I'm not doing something wrong, cuz these slashes look "broken" and it's rather bugging me... sorry to make such a trivial issue, but I wanted to make sure I didn't do something wrong:

![Weird Slashes](https://user-images.githubusercontent.com/495855/66153559-9c50a580-e5d0-11e9-9ff5-4da10620da11.png)

If they _are_ supposed to look that way... is there some way to get them to not to look like that in HTML next to an angle bracket?

**Comment by kiliman** [comment]
Yes, those are new ligatures.

You can turn those off by adding the file (`profiles.ini`) in your `./original` folder and re-building.

```ini
[default]
!less_slash.liga
!slash_greater.liga
```

This prevents these ligatures from being added to the font.

See the section on Customizing the generated font in the README file for more info.

**Comment by CWSpear** [comment]
Wow, awesome! Thank you so much!
