### ISSUE TITLE
Add operator-mono tag to this repo

### ISSUE THREAD

**Issue by mskelton** [kiliman/operator-mono-lig#120]
While we have the `ligature` and `fonts` tag on this repo, it may increase the discoverability of this repo by adding a tag of `operator-mono`.

**Comment by kiliman** [comment]
Done. Didn't realize you couldn't update.

**Comment by mskelton** [comment]
@kiliman I believe you have to have admin permissions on a repo to edit the tags and description.  Permissions are always tricky it seems 😄
