### ISSUE TITLE
Ligatures not working in Eclipse IDE

### ISSUE THREAD

**Issue by gavzla** [kiliman/operator-mono-lig#123]
Hi, I'm not able to see the ligatures in the Eclipse IDE under Mac OS Catalina 10.15.1

<img width="347" alt="Screen Shot 2019-11-27 at 4 05 17 PM" src="https://user-images.githubusercontent.com/11657368/69759289-bc639780-112f-11ea-8bed-bc2b5cc7ce6f.png">

**Comment by kiliman** [comment]
I don't use Eclipse. Are you able to use Fira Code with ligatures on Eclipse?

**Comment by gavzla** [comment]
Thank you for your inmediate response. I understand and yes, I'm able to see FiraCode and Victor Mono ligatures on it, only tested those 2.

Operator Mono:
<img width="399" alt="Screen Shot 2019-11-27 at 7 01 47 PM" src="https://user-images.githubusercontent.com/11657368/69767036-651df100-1148-11ea-9fa9-4da06ff4073b.png">

Fira Code:
<img width="399" alt="Screen Shot 2019-11-27 at 6 56 12 PM" src="https://user-images.githubusercontent.com/11657368/69766799-a235b380-1147-11ea-8fe6-112321e04178.png">

Victor Mono:
<img width="399" alt="Screen Shot 2019-11-27 at 6 58 25 PM" src="https://user-images.githubusercontent.com/11657368/69766952-2e47db00-1148-11ea-8ece-aaea5be32b15.png">

Although, I don't remember when was the last time I did the process to add the ligatures to Operator Mono font, maybe one or two years ago? Do you think I must do it again?

Thank again!

**Comment by kiliman** [comment]
Yes I would recommend you regenerate the ligatures. Make sure you reinstall
the Lig versions.

Can you also verify that the ligatures work in VS Code? Thanks.

**Comment by gavzla** [comment]
Update everything, now works great, sorry for the noise and hasle, I didn't remember that I generated the ligatures so much time ago:

<img width="399" alt="Screen Shot 2019-11-27 at 7 39 23 PM" src="https://user-images.githubusercontent.com/11657368/69768323-212dea80-114e-11ea-8c11-4fc29cb18351.png">

Thank you!

**Comment by kiliman** [comment]
Awesome. Glad you got it working.
