### ISSUE TITLE
Don't generate alternative profile

### ISSUE THREAD

**Issue by MrJmpl3** [kiliman/operator-mono-lig#128]
When you have alternative block in profile.ini, the command generate the ttx but don't the otf file

Edit: I use no Smart Screen versions

**Comment by kiliman** [comment]
Can you post your `profiles.ini` file for me? Thanks!

**Comment by MrJmpl3** [comment]
```
[default]

[Alt]
greater_equal.liga=greater_equal.2.liga
```

**Comment by kiliman** [comment]
Sorry for the late response, but v2.2.8 should fix the profile feature.

**Comment by kiliman** [comment]
Please reopen if this issue is not resolved.

**Comment by MrJmpl3** [comment]
> 
> 
> Please reopen if this issue is not resolved.

Hi! I again, the problem persists.
