### ISSUE TITLE
Request: Add cursive font for italic

### ISSUE THREAD

**Issue by phmatray** [kiliman/operator-mono-lig#129]
Hello, 
First of all thank you for the fantastic work on this V2.

Recently I discovered FiraCode iScript and I like very much to be able to put some words in cursive.
https://github.com/kencrocken/FiraCodeiScript

Here is an overview of my IDE
<img width="438" alt="Capture d’écran 2020-02-28 à 17 54 44" src="https://user-images.githubusercontent.com/9035444/75568405-81853e80-5a53-11ea-9a20-07c3a7cbc17e.png">

If it is possible to add ligatures from FiraCode, I suppose it is possible to add characters from other fonts. Would it be possible to do the same or add an option to modify Operator Mono Lig?

Thanks

**Comment by kiliman** [comment]
Operator Mono includes italics, so not sure what you are specifically asking for.

![image](https://user-images.githubusercontent.com/47168/75570549-584db980-5a25-11ea-9891-0f6d4de771cc.png)
