### ISSUE TITLE
Problems with SmartScreen on macOS

### ISSUE THREAD

**Issue by iStefo** [kiliman/operator-mono-lig#13]
Creating a new issue from this comment: https://github.com/kiliman/operator-mono-lig/issues/1#issuecomment-330352057

The problem exists at os level, as the following screenshot shows:

![screen shot 2017-09-19 at 00 02 13](https://user-images.githubusercontent.com/768764/30567798-530549b0-9cd2-11e7-8d49-1aa94a0074a5.png)

What files can I send you to help with this problem?

**Comment by kiliman** [comment]
Have you pulled the most recent version? I've verified that the generated fonts work fine in both Windows and macOS.

I even pushed Operator Mono SSm Medium Italic.

**Comment by iStefo** [comment]
I can confirm that I had already pulled from master as of yesterday evening (GMT+2), so that was not the problem.

I had already suspected that the problem may have been with my source font file since I had to manually rename the ScrenSmart versions to match the form expected by your scripts.
However, I was able to obtain a different copy of the SSm otf files from https://github.com/stephenp/dotfiles/tree/master/Fonts/HCo_OperatorMonoSSm/OpenType and it turns out that everything works as expected when using those files as inputs!

The difference is clear: 

<img width="512" alt="screen shot 2017-09-19 at 14 40 10" src="https://user-images.githubusercontent.com/768764/30592986-51c21408-9d49-11e7-997f-bc80d9c6430f.png">
(invalid version)

<img width="512" alt="screen shot 2017-09-19 at 14 40 11" src="https://user-images.githubusercontent.com/768764/30592997-5afb5afc-9d49-11e7-9c66-a789d3a70813.png">
(correct version)

**Comment by kiliman** [comment]
I'm glad you got it working. I had to remove the link to the original fonts since technically they shouldn't be posted online as they are not free fonts. 

That's the whole point of this project, otherwise I would have just posted the ligature versions directly.
