### ISSUE TITLE
I can't get the ligaments to work

### ISSUE THREAD

**Issue by FlatEarthGary** [kiliman/operator-mono-lig#132]
Hello there! I have a problem getting the ligaments and font to work. Help would be appreciated!

I have followed the instructions from the READ.md file. I have all the prerequisites installed and I have downloaded and unzipped the folder with all the contents. I have taken the original file that I want ligaments to, being Operator Mono Book Regular and changed it's name to OperatorMono-Book, and copied it into the original folder. 

I then ran "npm install" and then pressed the build batch file in the folder. This led to a new terminal popping up with a bunch of code and then the build folder was created. In the build folder there is "OperatorMonoLig-Book" as a OpenType font file and a "OperatorMonoLig-Book" TTX file. I have installed the "OperatorMonoLig-Book" as a font. Am I supposed to do something to the TTX file? Am I supposed to install the original font, Operator Mono Book Regular, alongside the "OperatorMonoLig-Book" or just "OperatorMonoLig-Book"?

Thank you for helping me out, have a great day!

**Comment by kiliman** [comment]
It looks like the fonts were correctly generated. The *OperatorMonoLig-Book* font is the one that you want to install. You could install the original one as well. They show up as two different fonts: *Operator Mono Book* and *Operator Mono Lig Book*.

Update your editor to use the *Operator Mono Lig Book* font and enable ligatures. For example in VS Code, your settings should look like this. Note the different spellings of font family for Mac vs Windows.

```json
{
  //@sync os=mac
  "editor.fontFamily": "OperatorMonoLig-Book",
  //@sync os=windows
  // "editor.fontFamily": "Operator Mono Lig",
  "editor.fontWeight": "400",
  "editor.fontLigatures": true,
}
```

Where `fontWeight` corresponds to following values:

- 100 Thin
- 200 Extra Light
- 300 Light
- 400 Normal/Regular/Book
- 500 Medium
- 600 Semi Bold
- 700 Bold
- 800 Extra Bold
- 900 Ultra Bold

**Comment by FlatEarthGary** [comment]
Thank you, got it working!
