### ISSUE TITLE
Italics doesn't work with Operator Mono

### ISSUE THREAD

**Issue by PedroFumero** [kiliman/operator-mono-lig#134]
I have 2 pc, I followed the process with the first one to install Operator Mono Lig, and it worked correctly. However on the second pc, I also followed the whole process, italic font styles are not being applied with the Operator Mono font, does anyone know what the problem may be?

PC 1 (It works well):
![pc1](https://user-images.githubusercontent.com/5423146/80913218-f5242000-8d10-11ea-836b-5e38fbca84a8.png)

PC 2 (It does not work):
![pc2](https://user-images.githubusercontent.com/5423146/80913196-ca39cc00-8d10-11ea-8dab-1dd01d82294b.png)

**Comment by kiliman** [comment]
Did you make sure you installed the italics version on the 2nd PC? What is different between the two computers? Sorry I just need more information.

**Comment by PedroFumero** [comment]
> Did you make sure you installed the italics version on the 2nd PC? What is different between the two computers? Sorry I just need more information.

Yes, of course, the 2 pcs have installed all operator fonts variations. Check the words (if, else) on both images, on second image are not applied styles

**Comment by kiliman** [comment]
The "italics" on PC 2 are not real. They are slanted by the OS because the font is missing. Try reinstalling the fonts.

**Comment by PedroFumero** [comment]
What source are you referring to? Original Operator Mono? because I have already installed it 3 times and still cannot see the results

**Comment by kiliman** [comment]
I'm assuming that you're using Visual Studio Code. When you specify a font such as Operator Mono Lig, then when the theme requires an italic version, it looks for Operator Mono Lig Italic. If it can't find it, it will simply slant the existing font.

So make sure you install all the ligature fonts.

**Comment by PedroFumero** [comment]
I have reinstalled everything from scratch and now it works properly. Thank you very much for the help.

**Comment by rasitiri** [comment]
I want to use Operator Mono Lig just like in computer1 image. But I don't know which version should I install.

**Comment by PedroFumero** [comment]
> I want to use Operator Mono Lig just like in computer1 image. But I don't know which version should I install.

You have to use light version, it means: Operator Mono Light Regular version. Regards
