### ISSUE TITLE
Can't get open circle %

### ISSUE THREAD

**Issue by likecreep** [kiliman/operator-mono-lig#139]
Hi, I'm using vscode and here is my profiles.ini:
```
# name of profile (one or more sections, first should be name default)
[default]
# glyph=altglyph
percent=percent.alt
greater_equal.liga=greater_equal.2.liga
less_equal.liga=less_equal.2.liga
```
But I can't get open circle %. The % is still the close circle version.

**Comment by kiliman** [comment]
Hm.. That's what I have. What about the >= and <= ... do they have the horizontal bar (alternate) or the slanted bar (default)? If you're not seeing those, then it looks like the `profiles.ini` file is not being processed. Make sure you put it in the `./original` folder.

**Comment by likecreep** [comment]
> Hm.. That's what I have. What about the >= and <= ... do they have the horizontal bar (alternate) or the slanted bar (default)? If you're not seeing those, then it looks like the `profiles.ini` file is not being processed. Make sure you put it in the `./original` folder.

I got the horizontal bar >= and <=. Only the % is not working.

**Comment by likecreep** [comment]
![image](https://user-images.githubusercontent.com/28685148/81179450-40258800-8fdc-11ea-9524-15bad208edca.png)

**Comment by likecreep** [comment]
The fonts I'm using are OperatorMono-Book and OperatorMono-BookItalic
![image](https://user-images.githubusercontent.com/28685148/81179678-92ff3f80-8fdc-11ea-8041-47bdb1f6fe4a.png)

**Comment by kiliman** [comment]
Ok, I see. I just re-ran it on my end and I no longer have the `percent.alt` so apparently something must have broken since I last ran it. :(

Anyway, I'll take a look and let you know when it's fixed. I like the open-circle percent also.

**Comment by kiliman** [comment]
Hmm.. regenerated my fonts to test the italics fix and now I see the `percent.alt` glyph.

Anyway, once I've merged in the italics fix, I'll try again to see if this is still working.

![image](https://user-images.githubusercontent.com/47168/81721865-881a3400-944e-11ea-90b2-88478b114810.png)

**Comment by kiliman** [comment]
Let me know if this is still happening. We can reopen if necessary.
