### ISSUE TITLE
Which font variant is supported?

### ISSUE THREAD

**Issue by kuntau** [kiliman/operator-mono-lig#140]
From what I read in the readme the following variants are supported?

```
Operator Mono SSm Light/Light Italic
Operator Mono SSm Book/Book Italic
Operator Mono SSm Medium/Medium Italic
Operator Mono SSm Bold/Bold Italic
Operator Mono Light/Light Italic
Operator Mono Book/Book Italic
```

but when I run the build, it only outputs 4 variants

```
OperatorMonoLig-Book.otf
OperatorMonoLig-BookItalic.otf
OperatorMonoLig-Light.otf
OperatorMonoLig-LightItalic.otf
```

None of the SSm variants got builds. Did I miss something?

**Comment by kiliman** [comment]
What are the filenames in the ./original folder?

It should be OperatorMonoSSm-Book.otf, etc.

![image](https://user-images.githubusercontent.com/47168/81572028-b295bf80-9370-11ea-87f2-029fd938ac7b.png)

**Comment by kuntau** [comment]
Here my fonts in original folder

![Screenshot 2020-05-11 at 10 21 40 PM](https://user-images.githubusercontent.com/327489/81572512-e3f4a680-93d5-11ea-8adf-08da19eb918b.png)

**Comment by kiliman** [comment]
It is in the README, but perhaps we need to make this more clear.

![image](https://user-images.githubusercontent.com/47168/81580859-f80bba00-937b-11ea-97fd-c184125c630c.png)
