### ISSUE TITLE
Operator Mono SSm fonts don't seem to respect profiles.ini

### ISSUE THREAD

**Issue by willfrey** [kiliman/operator-mono-lig#149]
The italic `underscore_underscore.liga` seems to over-extend to the left in VSCode, so I tried disabling it with `!underscore_underscore.liga` in `profiles.ini`. This seems to have fixed it for Operator Mono, but the ligature is still present in the SSm version.

Also, the master branch doesn't appear to be generating .otf files for alternative profiles anymore. I had to download the latest release (2.2.8) to get that to work.

Thanks!

**Comment by willfrey** [comment]
Nevermind! I just needed to reload VSCode and the new font renders correctly.

**Comment by kiliman** [comment]
Thanks. I'll check on the branch.
