### ISSUE TITLE
Suggestion: can you support light versions also?

### ISSUE THREAD

**Issue by sagarrabadiya** [kiliman/operator-mono-lig#15]
for ex. operator mono light

**Comment by kiliman** [comment]
Yes, I plan on adding all the weights. I'm working on Operator Mono Book (non-ScreenSmart) now. I'll then start on Light (ScreenSmart and regular).

**Comment by sagarrabadiya** [comment]
wonderful, Thank you so much.. waiting for it. :) 👍

**Comment by vikky49** [comment]
@kiliman  How do i build the fonts for just the Book and Book Italic .By default its only building the Medium and Medium Italic fonts

**Comment by kiliman** [comment]
@vikky49 Did you pull the latest version of the code?

If you run the `build` command it will try to build a font for every font that's defined in the `ligature` folder that you have in the `original` folder.

What's probably happening is that you don't have the ScreenSmart version of the Book weight. I haven't created the ligatures for the regular Book weight yet. I'm working on it now.

**Comment by bermanboris** [comment]
Thanks for the tool @kiliman! It's awesome! 

Is there any progress with the light version? Maybe we can help you somehow?

**Comment by kiliman** [comment]
I've started on Operator Mono SSm Light. Here's the regular version. Need to finish the italic.

Here's Operator Mono SSm Light at 14px in Visual Studio Code.

Note: I also added the F# fish operators >=> and <=<

![image](https://user-images.githubusercontent.com/47168/31030787-999baf9a-a524-11e7-8b2a-5a0669f46867.png)

**Comment by kiliman** [comment]
I pushed Operator Mono SSm Light. I'll push the italic version out as soon as I can. 

Enjoy!

**Comment by bermanboris** [comment]
Wow, that was fast. Thanks a lot!

**Comment by jparkrr** [comment]
Would also like the non-smartscreen version of light, when you get a chance.

**Comment by NicolaSansom** [comment]
@kiliman Any progress on the italic version?

**Comment by Orillian** [comment]
@kiliman Looking forward to the light and extra light versions of the non-smartscreen versions. These should have been in the original font from the start! Thanks a bunch for doing these!

**Comment by bbashy** [comment]
Just letting you know there's still interest in the `light` versions!

Using the book version right now and it's great with ligatures. :tada:

**Comment by jboothe** [comment]
Can't say enough about how great this tool is! Fine work. 🚀 

I too would love the `light` non-smartscreen versions. It must be good deal of work. I wish I could help out.

**Comment by kiliman** [comment]
Starting work on Operator Mono Light (the #2 weight on the poll). Sorry for the delay everyone.

These are all redone from scratch with the new process (see features/contextualsubst) branch.

These ligatures have more consistent spacing and better hints for smaller sizes.

Ignore the italics in the screenshot. Since I haven't started the italic version, VS Code is synthesizing italics from the regular style.

![image](https://user-images.githubusercontent.com/47168/39382431-73e72e6e-4a33-11e8-8e5b-4384c3b86cf7.png)

**Comment by jboothe** [comment]
@kiliman 
`./build.sh` does not appear to do anything.  
- pulled branch `features/contextsubst`
- `npm install` for good measure
- used both node v8.10.0 and v9.8.0

Running `./build.sh` in terminal completes sub-second and produces no output.

**Comment by kiliman** [comment]
The new branch only contains Operator Mono SSm Book for now. 

I should be finished with Operator Mono Light this weekend. I just wanted to let you know that I was finally back to working on the ligatures.

**Comment by kiliman** [comment]
Pushed initial version of Operator Mono Light to branch. It doesn't have all the ligatures but I wanted to verify the extract and build process for a second font.

Let me know what you think.

**Comment by kiliman** [comment]
I don't have the Linux subsystem installed, but I'm able to build from Windows 10.

Can you tell me what versions you have for Python and fonttools?

![image](https://user-images.githubusercontent.com/47168/39480924-ba412228-4d37-11e8-838d-9eb9820fb151.png)

**Comment by Orillian** [comment]
Not using the subsystem, it's a little too flakey for me at this point. 

What I am using is the really good optional Unix tools integration in the latest git-scm builds for Windows.

Python 2.7.14 ,fonttools 3.25.0, node 8.11.1

I'll be upgrading python to 2.7.15 and if that doesn't work I'll move over to 3.6.5 and let you know if anything changes.

**Comment by chantlong** [comment]
First of all, thank you for working on the ligature support for Operator Mono! Super cool!
I look forward to the completion of Operator Mono Lig Light with support for `===` `!==` 😀

**Comment by zhuguangxiang** [comment]
light version is not build
