### ISSUE TITLE
Italic font on comments

### ISSUE THREAD

**Issue by balduinofernando** [kiliman/operator-mono-lig#150]
Hi guys, I'm using **OperatorMonoLig-Book** as my main font, and it's working OK, but I wanted to display  **OperatorMonoLig-BookItalic** when I comment something or specifying an attribute.
Is it possible?
**_PS: My editor is VS Code._**

**Comment by mskelton** [comment]
@balduinofernando Apologies for the late reply, but this is something that you could be handled in one of two ways:

1. Find an editor theme that supports this out of the box.  I will shamelessly plug my [VS Code One Dark theme](https://marketplace.visualstudio.com/items?itemName=mskelton.one-dark-theme) 
1. Override the italic setting for specific scopes in your vscode settings.  This would look something like this.

```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "name": "Italic comments",
      "scope": ["comment"],
      "settings": {
        "fontStyle": "italic"
      }
    }
  ]
}
```
