### ISSUE TITLE
'ttx' is not recognized as an internal or external command on windows 10 x64

### ISSUE THREAD

**Issue by handhikadj** [kiliman/operator-mono-lig#151]
![image](https://user-images.githubusercontent.com/22522638/93984197-b4a36c80-fdad-11ea-88b2-3126d1b65467.png)

**Comment by kiliman** [comment]
Hmm... `ttx` is part of the fonttools package. It should be in a folder somewhere on the `%PATH%`

Can you show me where the commands are using the `where` command?

![image](https://user-images.githubusercontent.com/47168/94032195-b2311a80-fd8d-11ea-9d35-41048c720e75.png)

**Comment by handhikadj** [comment]
this is what I got:
![image](https://user-images.githubusercontent.com/22522638/94092193-4d84c700-fe44-11ea-8bec-81c3e703d17b.png)

**Comment by handhikadj** [comment]
turns out you're right. fixing my PATH sorts this out
