### ISSUE TITLE
"editor.renderWhitespace": "all" doesn't work with me

### ISSUE THREAD

**Issue by TyNguyen2k1** [kiliman/operator-mono-lig#152]
![Screenshot 2020-09-26 220522](https://user-images.githubusercontent.com/64082226/94343736-665bcb00-0044-11eb-934b-1f811a14a7f9.jpg)
My settings.json

    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Shades of Purple",
    "code-runner.runInTerminal": true,
    "code-runner.saveFileBeforeRun": true,
    "editor.lineNumbers": "relative",
    "workbench.colorCustomizations": {
        "editorLineNumber.activeForeground": "#FAD000",
        "editorUnnecessaryCode.border": "#f9267387",
        "editorWhitespace.foreground": "#FFFFFF00"
    },
    "terminal.integrated.fontSize": 13,
    "window.zoomLevel": 0.8,
    "editor.renderControlCharacters": false,
    "editor.minimap.enabled": true,
    "editor.renderLineHighlight": "all",
    "zenMode.hideLineNumbers": false,
    "zenMode.hideStatusBar": false,

    // Theme Setup.
    "editor.fontFamily": "Operator Mono SSm Lig, Menlo, Monaco, 'Courier New', monospace",
    "terminal.integrated.fontFamily": "'Operator Mono SSm Lig', 'Inconsolata for Powerline', monospace",
    "editor.fontSize": 15,
    "editor.lineHeight": 24,
    "editor.letterSpacing": 0.5,
    "editor.fontWeight": "400",
    "editor.fontLigatures": true,
    "editor.cursorStyle": "line",
    "editor.cursorWidth": 3,
    "editor.cursorBlinking": "solid",
    "editor.renderWhitespace": "all",
    "editor.snippetSuggestions": "top",
    "workbench.startupEditor": "newUntitledFile",
    "editor.glyphMargin": true,
    "workbench.editor.enablePreview": false,
    "explorer.confirmDragAndDrop": false,
    "files.trimTrailingWhitespace": true,
    "files.trimFinalNewlines": true,
    // Formatting Optional.
    "editor.formatOnSave": true,
    "prettier.eslintIntegration": true,
    "eslint.run": "onType",
    "eslint.autoFixOnSave": true,
    // MacOS Only Settings.
    "workbench.fontAliasing": "auto",
    "terminal.integrated.macOptionIsMeta": true,
    "workbench.statusBar.feedback.visible": false,
    // The default syntax (TextMate) highlighter classifies many tokens as variables and these are now (since VSCode 1.43) resolved into namespaces, classes, parameters, and so on. This is called Semantic highlighting support for TypeScript and JavaScript. But many themes and language extensions seem broken with single-colored syntax. This came as a surprise to me. It's set `true` by default. I recommend disabling this for now.
    "editor.semanticHighlighting.enabled": false,
    // SOP's highlight matching tag setting.
    "highlight-matching-tag.styles": {
        "opening": {
            "full": {
                "highlight": "rgba(165, 153, 233, 0.3)"
            }
        }
    },
    // SOP's Import Cost Extension Settings.
    "importCost.largePackageColor": "#EC3A37F5",
    "importCost.mediumPackageColor": "#B362FF",
    "importCost.smallPackageColor": "#B362FF",

    "sync.gist": "778d84ac46c3c0a2e0928131116953d8",
    "mssql.connections": [
        {
            "server": "DESKTOP-QSPIDEH\\SQLEXPRESS",
            "database": "",
            "authenticationType": "Integrated",
            "profileName": "Ty_Nguyen",
            "password": ""
        }
    ],
    "mssql.queryHistoryLimit": 50,

    "bracket-pair-colorizer-2.showHorizontalScopeLine": true,
    "bracket-pair-colorizer-2.highlightActiveScope": true,
    "bracket-pair-colorizer-2.forceUniqueOpeningColor": true,
    "bracket-pair-colorizer-2.activeScopeCSS": [
        "borderStyle : solid",
        "borderWidth : 4px",
        "borderColor : rgba(165, 153, 233, 0.3)",
        "opacity: 1.0"
    ],

    "todo-tree.highlights.customHighlight": {
        "TODO": {
            "icon": "check",
            "background": "#ffab00",
            "foreground": "white",
            "iconColour": "#ffab00",
            "gutterIcon": true
        },
        "FIXME": {
            "foreground": "white",
            "background": "#f92672",
            "iconColour": "#f92672",
            "gutterIcon": true
        }
    },
    "todo-tree.tree.showScanModeButton": true,

    "editor.columnSelection": false,

    "tabnine.experimentalAutoImports": true,
    "breadcrumbs.enabled": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",

    "java.home": "C:\\Program Files\\AdoptOpenJDK\\jdk-14.0.1.7-hotspot",
    "java.semanticHighlighting.enabled": true,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "java.help.firstView": "gettingStarted",
    "java.refactor.renameFromFileExplorer": "autoApply",
    "maven.terminal.useJavaHome": true,

    "C_Cpp.updateChannel": "Insiders",

    "faker.locale": "vi",

    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",

    "code-runner.executorMap": {
        // "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
        "java": "cd $dir && javac $fileName -d .\\out && java -classpath .\\out $fileNameWithoutExt"
    },

    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[sql]": {
        "editor.defaultFormatter": "ms-mssql.mssql"
    },

    "prettier.tabWidth": 4,

    "liveServer.settings.donotShowInfoMsg": true,

    "open-php-html-js-in-browser.selectedBrowser": "Chrome",
    "open-php-html-js-in-browser.documentRootFolder": "C:\\xampp\\htdocs\\",

    "vscode-neovim.neovimExecutablePaths.win32": "C:\\Program Files\\Neovim\\bin\\nvim.exe",

    "editor.quickSuggestions": true,
    "editor.suggestOnTriggerCharacters": true,
    "editor.tabCompletion": "on",
    "emmet.triggerExpansionOnTab": true,
    "extensions.ignoreRecommendations": false

**Comment by mskelton** [comment]
There is work being done to fix these issues, but it will still be a while before it will be done.  I'm closing this to keep the italic issues consolidated, but feel free to checkout some of the other two active italic issues: https://github.com/kiliman/operator-mono-lig/issues/154 and https://github.com/kiliman/operator-mono-lig/issues/157.

**Comment by kiliman** [comment]
Finally got the italics to work properly. Turns out that the fonttools program allows you to import feature (.fea) files which have all the instructions on how to generate the substitution tables. No need to build my own.

This fix is in the v2.4 release https://github.com/kiliman/operator-mono-lig/releases/tag/v2.4.0
