### ISSUE TITLE
When Using Ssm Variants, Spaces Take Up Half The Width

### ISSUE THREAD

**Issue by danlugo92** [kiliman/operator-mono-lig#156]
4 spaces become 2
2 spaces become 1
etc

![Screen Shot 2020-11-12 at 11 41 40 AM](https://user-images.githubusercontent.com/32064271/98961627-25c4ed80-24dc-11eb-9e76-3539c1728d84.png)
![Screen Shot 2020-11-12 at 11 42 08 AM](https://user-images.githubusercontent.com/32064271/98961632-28274780-24dc-11eb-98df-4be3ca9c97cd.png)

**Comment by kiliman** [comment]
That's a new one. Can you show me what it looks like for plain Operator Mono SSm without ligatures?

It's working fine for me. I use 2-space "tabs"
![image](https://user-images.githubusercontent.com/47168/98963490-b0eeb500-24d5-11eb-8135-b34b023f153a.png)

**Comment by danlugo92** [comment]
![Screen Shot 2020-11-24 at 1 17 19 PM](https://user-images.githubusercontent.com/32064271/100129059-6b2bd800-2e57-11eb-8a3b-7a9740fc46f7.png)
![Screen Shot 2020-11-24 at 1 16 53 PM](https://user-images.githubusercontent.com/32064271/100129073-6f57f580-2e57-11eb-84b4-c4f16e5f6f87.png)

**Comment by kiliman** [comment]
From what you show, Operator SSm is NOT the mono version. That's why the spacing is off.

**Comment by danlugo92** [comment]
@kiliman 

Ohhh, for some reason I assumed there was no non-mono version 🤦 .

Thanks, will try again with the correct variants.

**Comment by mskelton** [comment]
It appears that this is not an issue with this repository, but the font files that were used, so I'm going to close this issue.  If the issue persist, please let us know and we will re-open this issue.
