### ISSUE TITLE
Helping YT video

### ISSUE THREAD

**Issue by jhanikhilnath** [kiliman/operator-mono-lig#158]
Please add a video that shows all the steps as I am sure that some people like me are not able to follow the steps correctly and get messed up.

**Comment by kiliman** [comment]
I'm sorry to hear you're having issues building the fonts. I don't have time to make a video, but I could provide a more detailed guide with screenshots.

Is there any particular step that you're having issues with?

Thanks!

**Comment by jhanikhilnath** [comment]
I have all the requirements installed then I do `npm install` npm does its thing then i do `./build.sh` it creates an empty folder and nothing happens please add some screen shots and a step by step `readme.md` for installation 

Thanks

**Comment by kiliman** [comment]
Did you copy *your* Operator Mono fonts to the `./original` folder? Those are the fonts the build tool will patch to include ligatures. If it can't find them, there's nothing to build.

**Comment by jhanikhilnath** [comment]
Yes, I did

**Comment by jhanikhilnath** [comment]
Hey,

Still haven’t heard back from you.
Please just add a detailed guide if you can’t make a video.

Thanks

**Comment by mskelton** [comment]
@jhanikhilnath I can appreciate your frustration with the fonts not working for you, but please remember that @kiliman has put in a tremendous amount of effort into this repository without being paid for doing so.  Most open source maintainers have full time jobs, family's, and other commitments that they also have to manage, often leaving little time to keep up with projects like this.  We would like to help you resolve your issue, but I would just kindly ask for some patience and understanding.  Thanks!

Regarding the issue you are experiencing, could you send a screenshot of the files in the `./original` folder as well as a screenshot of the output when running `./build.sh`?  This will help us to more easily debug the issue.

**Comment by jhonstn** [comment]
@jhanikhilnath In my case, the problem is that fonttools was not installed in the path, but in ~/.local/bin. I had to add it to my .zshrc and so, it works.

ps: Sorry for the bad english :/
