### ISSUE TITLE
Add fish operator >=> for F#

### ISSUE THREAD

**Issue by kiliman** [kiliman/operator-mono-lig#16]
Add fish operator >=> for F#

**Comment by kiliman** [comment]
Can you add as a separate request? It will be easier to track that way. Thanks!

Currently the way the build process works, all weights have to have a specific ligature. I need to update it so it checks to see which ones are present.

I'm also planning to have a way to create language specific fonts so you can specify which ligatures to include.

**Comment by Orillian** [comment]
Done! #25

**Comment by kiliman** [comment]
The ligatures have been included in the new branch features/contextsubst.

NOTE: This only includes the Operator Mono ScreenSmart Book and Book Italic versions. This update was mainly for testing the new build process.
