### ISSUE TITLE
italic <= (less_equal.2.liga) slanted in wrong direction

### ISSUE THREAD

**Issue by kufii** [kiliman/operator-mono-lig#160]
![image](https://user-images.githubusercontent.com/4913552/102530319-20286d80-406f-11eb-83c5-5c705fddb1f5.png)

**Comment by kiliman** [comment]
Oops that's embarrassing 😳

Some of the ligatures were simply flipped horizontally to make the other glyph. Apparently the italic slant was also inverted.

I'll fix these. I noticed some others as well. Like `<|` and `|>`.
