### ISSUE TITLE
Erro on VSCODE - letter spacing 0?

### ISSUE THREAD

**Issue by FeehGb** [kiliman/operator-mono-lig#162]
When I set 
"editor.fontFamily": "Operator Mono SSm Lig", in setting.json
It Happens...!

![image](https://user-images.githubusercontent.com/43045359/106497350-b0463900-649c-11eb-8d27-5c083e38194c.png)

Can anyone Help me ?

**Comment by FeehGb** [comment]
If I remove all the other settings it remains the same way

**Comment by kiliman** [comment]
I'm assuming you're referring to the line numbers.

I'm not having any issues on my computer. Can you post a screenshot of some actual text? Does it look correct to you?

![image](https://user-images.githubusercontent.com/47168/106499349-7bcb8080-648e-11eb-8881-63e420b34113.png)

**Comment by FeehGb** [comment]
In sample.js
![image](https://user-images.githubusercontent.com/43045359/106607870-8cd5c980-6542-11eb-87ca-8416f09174a3.png)
It looks like the letter-spacing, tab and space bugs

**Comment by kiliman** [comment]
That looks like an issue with your original font. What does it look like when you select "Operator Mono SSm" (without ligatures)?

**Comment by FeehGb** [comment]
**What does it look like when you select "Operator Mono SSm" (without ligatures)?**
- Nothing

I remove all settings in settings.json
and put only "editor.fontFamily": "Operator Mono SSm Lig".
and nothing changes.
_Could be some extension ?_

**Comment by kiliman** [comment]
I mean, use "Operator Mono SSm". (No Lig).

That's the original font. Does it look normal? Or is the spacing wrong with it as well.

In other words, have you seen it work before you added the ligatures?

**Comment by FeehGb** [comment]
I works fine.

![image](https://user-images.githubusercontent.com/43045359/106808077-b24cfb00-6648-11eb-9153-43ed392aeeef.png)

**Comment by kiliman** [comment]
But you're not using "Operator Mono SSm" (ScreenSmart). You're using regular "Operator Mono".

![image](https://user-images.githubusercontent.com/47168/106810487-03ee8900-663b-11eb-8e51-fe2e625da28f.png)

Remember, this tool simply patches your existing fonts.

Operator Mono => Operator Mono Lig
Operator Mono SSm => Operator Mono SSm Lig

Make sure "Operator Mono SSm" is working properly before you used the patched version.

I've noticed other people have issues with their fonts, especially those they've downloaded online.

**Comment by FeehGb** [comment]
But that is the problem, when I change to Operator Mono SSm Lig in editor fontFamily
Happens the problem =/
the image example is what happens when I set "editor.fontFamily": "Operator Mono SSm Lig".

**Comment by kiliman** [comment]
Seriously, what happens when you use:

    "editor.fontFamily": "Operator Mono SSm",

NO LIG please.

**Comment by FeehGb** [comment]
![image](https://user-images.githubusercontent.com/43045359/106813731-29d25880-6650-11eb-827a-817beeb3a1c2.png)
it happens

**Comment by kiliman** [comment]
Well, that's why it's not working. That is NOT Operator Mono SSm. It looks more like Operator (with proportional spacing, not monospaced). You can tell because each letter takes up a different amount of space.

You need the correct font in order for the ligatures to work.
