### ISSUE TITLE
Operator Mono SSm Lig Book does not work with Vscode

### ISSUE THREAD

**Issue by tynguyen2k1** [kiliman/operator-mono-lig#164]
Looks like my Operator Mono SSm Lig Book font doesn't work with Vscode
![bandicam 2021-04-11 20-08-11-846](https://user-images.githubusercontent.com/64082226/114305394-3d8fb480-9b02-11eb-8e3a-84d3e70f33b8.gif)

**Comment by kiliman** [comment]
Put single quotes around your font name, if you have multiple fonts. Also remove "Book". Use fontWeight instead.

![image](https://user-images.githubusercontent.com/47168/114400336-d7417b00-9b6f-11eb-8db8-48260c350f22.png)

**Comment by TyNguyen2k1** [comment]
> Put single quotes around your font name, if you have multiple fonts. Also remove "Book". Use fontWeight instead.
> 
> ![image](https://user-images.githubusercontent.com/47168/114400336-d7417b00-9b6f-11eb-8db8-48260c350f22.png)

Looks like it doesn't work
![image](https://user-images.githubusercontent.com/64082226/114409184-5f596c00-9bd4-11eb-9883-ec30fa9b769b.png)

**Comment by kiliman** [comment]
That looks like the correct font to me. What does it look like with actual source code?

**Comment by TyNguyen2k1** [comment]
![image](https://user-images.githubusercontent.com/64082226/114411392-55386d00-9bd6-11eb-9464-1e31d72d8779.png)

**Comment by kiliman** [comment]
Again, you need to remove the weight from the fontFamily. It should only be "Operator Mono SSm Lig".

This screenshot looks good. See, you removed the "Book". You re-added it in the other screenshot.
![image](https://user-images.githubusercontent.com/64082226/114409184-5f596c00-9bd4-11eb-9883-ec30fa9b769b.png)

And when I say "source code" I mean something like this, not the settings.json.

![image](https://user-images.githubusercontent.com/47168/114411908-9dc23d00-9b7a-11eb-8957-c59fc40685a5.png)

**Comment by Helfull** [comment]
hey, i also having problems with the in vscode here is a sourcecode how it looks in PHP
![image](https://user-images.githubusercontent.com/720645/114846100-a31ec200-9ddc-11eb-8ae4-5bbe0d1ab48b.png)

as you can see the `->` and `++` as well as `--` are not correct

**Comment by kiliman** [comment]
Hmm.. I installed Palenight Theme (selected Palenight Operator).

![image](https://user-images.githubusercontent.com/47168/114893406-a9606e80-9ddb-11eb-881b-b5e406d97fe1.png)

**Comment by Helfull** [comment]
okay, reinstalling everything and moving to my macbook to generate the fonts did work. i guess the problem was some version conflict on my windows system.

It is working now, for me!

**Comment by ahane** [comment]
for me the correct font name was 'Operator Mono Lig' (no ssm)
