### ISSUE TITLE
Build script doesn't do anything

### ISSUE THREAD

**Issue by TheBotlyNoob** [kiliman/operator-mono-lig#165]
I have tried it on `wsl` and `cmd`. The script does nothing except create the `build` directory with nothing in it.

**Comment by kiliman** [comment]
Did you put the Operator Mono .otf files into the `./original` folder?

**Comment by TheBotlyNoob** [comment]
yes

**Comment by kiliman** [comment]
Can you do a screenshot of the directory listing? As the README states, the filenames must not include spaces and should look like this:

- OperatorMonoSSm-Book.otf
- OperatorMonoSSm-BookItalic.otf
- OperatorMono-Light.otf
- OperatorMono-LightItalic.otf
- etc.

https://github.com/kiliman/operator-mono-lig#installation

**Comment by TheBotlyNoob** [comment]
wait, im dumb, my filenames have spaces

**Comment by TheBotlyNoob** [comment]
it works

**Comment by TheBotlyNoob** [comment]
Thank you
