### ISSUE TITLE
Glyphs are way too small

### ISSUE THREAD

**Issue by omar-salama** [kiliman/operator-mono-lig#172]
<img width="424" alt="Screen Shot 2021-09-11 at 02 06 33" src="https://user-images.githubusercontent.com/31420520/132929223-8afaa3c1-baa4-4822-84f1-d53f8b2df815.png">
Built with latest script and on MacOS.

**Comment by kiliman** [comment]
Yes that is definitely not right. 

Is this VS Code? Can you open the sample.js file and post a screenshot?

Thanks

**Comment by omar-salama** [comment]
It had something to do with the font files.
I forgot where the originals (otf) were, so I converted the ttf I have to otf (which produced the problem).
Ran the script again with the original otfs and the problem went away. Probably bad file conversion or something.
If you would like to investigate further, just let me know.

**Comment by kiliman** [comment]
I’m glad you figured it out.
