### ISSUE TITLE
npm install always giving errors

### ISSUE THREAD

**Issue by AMAlonso64** [kiliman/operator-mono-lig#175]
I can't get npm to install the dependencies and the build script will not work. I've tried using the docker version as well as the manual version and I get the same error in both (attached in screenshot). Can someone please help?
![Screen Shot 2021-11-27 at 5 44 16 PM](https://user-images.githubusercontent.com/61603775/143689762-3ac9f2d8-801a-4236-964b-6f9cfd602a37.png)
![Screen Shot 2021-11-27 at 5 45 03 PM](https://user-images.githubusercontent.com/61603775/143689766-e57c8ded-cb68-4b43-9038-38338b82654e.png)

**Comment by AMAlonso64** [comment]
I solved it in the "manual" version by reinstalling npm.

**Comment by kiliman** [comment]
Glad you got it working 👍

**Comment by aacassandra** [comment]
remove package-lock.json and rum npm i.
