### ISSUE TITLE
Create `::` ligature

### ISSUE THREAD

**Issue by luciascarlet** [kiliman/operator-mono-lig#177]
## Request preferences

* Weight requested: SSm Book mainly, but it would be nice to also have it for Book Italic, Medium and Medium Italic.

## Ligature description

A lot of ligature fonts have a ligature for `::` where the colons are just slightly closer together. I find that this really helps readability for C++ and Rust code, where it's used for namespacing, and it's also nice in some functional languages that use it as an operator such as F#. It shouldn't be that difficult to create, but unfortunately I have no idea how to create a new ligature for this myself in Glyphs, so I'm requesting it here. Here are some screenshots demonstrating this ligature in other fonts (first screenshot is Operator Mono SSm Lig, which does not feature it)

<img width="409" alt="Operator Mono SSm Lig" src="https://user-images.githubusercontent.com/13824526/145037405-ed5ae4a1-7e35-49a6-ac97-5892b16a2743.png">
<img width="360" alt="Recursive Code" src="https://user-images.githubusercontent.com/13824526/145037402-0bc0e93e-917a-4991-9c26-b46d3e2d055f.png">
<img width="365" alt="JetBrains Mono" src="https://user-images.githubusercontent.com/13824526/145037392-3f61906d-4f21-461e-a0f3-29a63ad3615f.png">
<img width="286" alt="PragmataPro" src="https://user-images.githubusercontent.com/13824526/145037395-29bf5855-58bf-4104-a7ff-dba3a2bc9a73.png">
<img width="319" alt="Cascadia Code" src="https://user-images.githubusercontent.com/13824526/145037398-efbc144a-d3ac-4c7e-a75a-6291edb0bff2.png">
<img width="338" alt="Fira Code" src="https://user-images.githubusercontent.com/13824526/145037399-81529e20-cc3e-4277-b570-689b938524f3.png">

---

### Ligature variations 

Due to how development is handled, not all ligatures are created at the same time. However, we will get to them all eventually. If you would like to help us develop ligatures, please reach out to us via email at kiliman@gmail.com

#### Operator Mono

- [ ] XLight
- [ ] XLight Italic
- [ ] Light
- [ ] Light Italic
- [ ] Book
- [ ] Book Italic
- [ ] Medium
- [ ] Medium Italic
- [ ] Bold
- [ ] Bold Italic

#### Operator Mono SSm

- [ ] SSm Light
- [ ] SSm Light Italic
- [ ] SSm Book
- [ ] SSm Book Italic
- [x] SSm Medium
- [ ] SSm Medium Italic
- [ ] SSm Bold
- [ ] SSm Bold Italic

**Comment by dannymcgee** [comment]
I write a lot of Rust and C++, so I made this myself in a local fork. (I don't have a Mac or I would have offered to contribute it.)

@kiliman If it's useful at all, here's my glyph definition for Medium SSm:
```xml
<Glyph name="colon_colon.liga" lsb="-291" width="625">
  <CharString name="colon_colon.liga">
    0 155 201 156 hstem
    226 169 -161 168 vstem
    -113 356 rmoveto
    2 156 rlineto
    -168 hlineto
    -2 -156 rlineto
    411 hmoveto
    168 hlineto
    2 156 rlineto
    -168 hlineto
    -12 -512 rmoveto
    169 hlineto
    5 155 rlineto
    -169 hlineto
    -247 -155 rmoveto
    5 155 rlineto
    -169 hlineto
    -5 -155 rlineto
    endchar
  </CharString>
</Glyph>
```
I didn't make an italic version or any other weights out of sheer laziness lol. Here's what it looks like:

![colon_colon_lig](https://user-images.githubusercontent.com/13191586/145053498-394e26bf-c807-42f0-97fc-4ba1536b94a7.png)

**Comment by kiliman** [comment]
@dannymcgee Nice. How did you manage to create the glyph without the Glyphs app?

**Comment by dannymcgee** [comment]
> @dannymcgee Nice. How did you manage to create the glyph without the Glyphs app?

It's been a little while so I honestly don't remember the exact steps, but I used a trial version of FontLab 6 to do the actual editing. From there, I exported the modified font to OTF, used one of the commands in this repo to convert to TTX, and IIRC I just manually hunted through the TTX file to find the correct attributes and created a new XML file matching the format of the others. Not really the most elegant workflow lol, but it did the trick.

**Comment by kiliman** [comment]
@dannymcgee Ha. Impressive 👏

It's been a while since I've updated the ligatures, so I'll see if I can block out some time this weekend and work on some of the requests.

**Comment by luciascarlet** [comment]
@dannymcgee Off-topic, but what syntax theme is that? Looks like a variation of Palenight but with more violet keywords, I dig it.

**Comment by dannymcgee** [comment]
> @dannymcgee Off-topic, but what syntax theme is that? Looks like a variation of Palenight but with more violet keywords, I dig it.

Thanks! It's actually my own: https://marketplace.visualstudio.com/items?itemName=dannymcgee.summer-vacation-theme

**Comment by luciascarlet** [comment]
@dannymcgee Oh that looks great, I've actually been working on a custom one myself ([Letty](https://github.com/LettyTheme)) but it's currently only fully implemented in Xcode. I will say this though, bless you for making a matching light theme; not enough themes do this and as someone who uses both light and dark mode depending on daytime I _really_ appreciate that. (This was one of the key design goals for my theme)

**Comment by kiliman** [comment]
I use Cobalt2 by Web Bos. He's the one that got me hooked on Operator Mono. It looks great with ligatures

![image](https://user-images.githubusercontent.com/47168/145430002-d1ebbfce-c279-4f24-8acf-04124236f829.png)

**Comment by dannymcgee** [comment]
@kiliman Ha, seeing your screenshots here actually inspired me to use blue instead of gray for doc comments. Cobalt2 is really nice.

**Comment by kiliman** [comment]
Yeah, dark themes don't all have be shades of gray. That's why I prefer Twitter's dark mode over GitHub's. I actually use an extension called Stylus, so I can theme code on GitHub with Cobalt2.

Actual screenshot from GitHub
![image](https://user-images.githubusercontent.com/47168/145450860-d67659bb-ec08-4ac0-bbe2-a4af2c8354bd.png)
