### ISSUE TITLE
Ligatures need better hinting 

### ISSUE THREAD

**Issue by ivancuric** [kiliman/operator-mono-lig#18]
Compared to Fira Code, the ligatures aren't as readable on a non-retina display.

Most of them are blurry and stuck together.

![image](https://user-images.githubusercontent.com/2827047/30850783-ed0c66c2-a2a6-11e7-9688-2c63166010ea.png)

**Comment by kiliman** [comment]
I set my font size to 16+ pixels, so it doesn't affect me much, but I agree that I need to do a better job at smaller sizes.

This is the first time I've done any font work at all, so it's definitely been a learning experience. I actually received some tips from the guy that wrote the Glyphs app. Now that I have the basic process down, I'm going to go back and redo the ligatures. I'll see what I can do about adding better hinting.

I'll add more spacing between the less than/greater than and the lower bar. I also want to open up the === ligature. The lines tend to jump around.

Thanks for your feedback. I appreciate you checking it out.

**Comment by Orillian** [comment]
14 pixels seems to be fine for the most part but there are weird spacing issues at 13 and 12 Mostly where the ligature seems lopsided or where spacing between the lines in === for example are not even. I'm guessing that's what you mean by "jump around!". Either way, using the regular non screen smart version at 14px, is still better than not having the ligatures!

**Comment by kiliman** [comment]
I've had better luck when I increased the distance between the horizontal bars (like the Light weight). I'm going to back and redoing all the ligatures and try to get more consistency in spacing.

**Comment by kiliman** [comment]
The ligatures have been completely redone with better hinting. This is available in the new branch features/contextsubst.

NOTE: Only Operator Mono SSm Book and Book Italic have been done. I was testing the new build process

Original versions
![image](https://user-images.githubusercontent.com/47168/39335002-2e0ad328-497f-11e8-81f5-d53662f1edf6.png)


New hinted versions
![image](https://user-images.githubusercontent.com/47168/39334776-1038e372-497e-11e8-81cd-c1a6d78645b3.png)
