### ISSUE TITLE
Only two fonts in build folder

### ISSUE THREAD

**Issue by Jeferson-Emanuel** [kiliman/operator-mono-lig#180]
After renaming all the fonts following the name format recommended and running the build commando, I got only 4 files in the build folder:

OperatorMonoLig-BookItalic.otf
OperatorMonoLig-LightItalic.otf
OperatorMonoLig-BookItalic.ttx
OperatorMonoLig-LightItalic.ttx

Running Windows 10.

**Comment by Jeferson-Emanuel** [comment]
Sorry for not updating here previously. I followed the instructions in issue #169 and renamed the files following the model you posted there.

My original folder look like this:

![image](https://user-images.githubusercontent.com/40230023/169281730-63f3cc5e-8cf2-4f62-ba69-c5b5741a985e.png)

My build folder look like this now:

![image](https://user-images.githubusercontent.com/40230023/169281847-f14090cf-a7d5-440e-891a-61d74fa35e96.png)

After installing them, I tried to use the Operator Mono SSM Lig and got this:

![image](https://user-images.githubusercontent.com/40230023/169282108-1dbcd3a0-d236-4cf1-af7e-2adcaa47b1eb.png)

Seems like only the de non SSM versions work with the ligatures.

This is what I see in my Fonts folder:

![image](https://user-images.githubusercontent.com/40230023/169282372-02892976-03ff-4d14-9c57-48513aca904c.png)

**Comment by Jeferson-Emanuel** [comment]
Interesting. I probably messed up when I was copying the names from your model and pasting in the font names in the original folder.

I will look in the name inside the files to find the correct ones, rename it the right way and run the build.bat again. 

Thanks.

**Comment by Jeferson-Emanuel** [comment]
Updating here. All working now. I really had renamed the wrong font files.

A suggestion to avoid further issues with it would be to make your script detect which font is which automatically. The need to rename the files in a very specific and exact way will be prone to errors by the user.

Thanks. =)

**Comment by kiliman** [comment]
Hmm.. well that's how the fonts were named when I purchased them, so not sure why it would be a problem.

Anyway, glad you figured it out.
