### ISSUE TITLE
Does not work with Python 2.7 shipped with MacOS Montery

### ISSUE THREAD

**Issue by nickbarrow** [kiliman/operator-mono-lig#181]
Unfortunately I do not have the terminal output of attempting to install fonttools with py 2.7, however it initially appeared successful.

When trying to run ./build.sh I got:
`'ttx' is not recognized as an internal or external command`
`'fonttools' is not recognized as an internal or external command`

Resolved issue by installing latest Python 3.10.7 release for MacOS, then running
`pip3 install fonttools`

No assistance required, but I feel the readme should be updated to reflect this.

Thanks for the tool, worked great!

**Comment by kiliman** [comment]
Awesome. I'll update the README.
