### ISSUE TITLE
Copy your Operator Mono OpenType files into the original folder.

### ISSUE THREAD

**Issue by bajras** [kiliman/operator-mono-lig#19]
Not really an issue but wanted to ask a question. Where does Operator Mono OpenType files live? and copy to original folder(what is this original folder)? Thanks.

**Comment by kiliman** [comment]
Since the Operator Mono fonts are not free, I can't distribute them. You need to place your .OTF files into the ./original folder. The script will then merge the ligatures into the original fonts to create the new fonts in the ./build folder.

Hope that makes sense.

**Comment by bajras** [comment]
I have the operator fonts, ah got it. The original folder lives inside the cloned folder and the new font will come in to the build folder once I run the build script? Thanks Im getting excited to use this in my VScode and Thanks for the quick response as well. Cheers.

**Comment by kiliman** [comment]
Yes. Let me know if you have any questions. Good luck!

**Comment by bajras** [comment]
One more question, I ran sh build.sh and it created the build folder but its empty. I added below font to the original folder: 

- Operator Mono Bold Italic.otf
- Operator Mono Bold Regular.otf
.....

**Comment by kiliman** [comment]
Ah. Unfortunately that's one of the font weights that I haven't completed yet.

If you look in the README (as well as the ./ligature folder), you'll see which ones I've already done.

The only non-ScreenSmart font that I've done is the Medium weight. Try that one and see if it's usable. You could technically copy the Medium weight and merge it into the Bold weight. You simply need to update the names.xml file. The ligatures will be a little thinner, but will still take the same horizontal space. 

You can't mix and match the ScreenSmart fonts though, as they use a width of 625 units vs 550.

It will probably be a while before I can get to the Bold weight though.

**Comment by bajras** [comment]
Ok, thats fine I wont be using the Bold ones and had Operator Mono Medium Italic.otf and Operator Mono XLight Italic.otf in the ./original folder as well but it didnt convert those? Should I remove the bold ones and just put the two font I mentioned just now? Also looks like the ./ligature folder names have no space but my font file name has space to it does it matter? Below are some screenshot of what im doing. 

![screen shot 2017-10-04 at 11 05 12 am](https://user-images.githubusercontent.com/3359989/31186305-e56305cc-a8f3-11e7-9e8c-f0a84fff3e4d.png)
![screen shot 2017-10-04 at 10 54 02 am](https://user-images.githubusercontent.com/3359989/31186354-05c8c874-a8f4-11e7-9c01-ae403768c808.png)

**Comment by bajras** [comment]
I just added Operator Mono Medium Italic.otf & Operator Mono Medium Regular.otf in the original folder and ran the sh build.sh still not luck.

**Comment by bajras** [comment]
Tried with Operator SSm as well no luck. 
![screen shot 2017-10-04 at 11 26 23 am](https://user-images.githubusercontent.com/3359989/31187231-e78353fe-a8f6-11e7-83ac-64d98982ce68.png)

**Comment by kiliman** [comment]
Hmm... odd my filenames didn't have the spaces. Just rename them to match these.

![image](https://user-images.githubusercontent.com/47168/31187868-28c4cf50-a901-11e7-8620-c65befd9a394.png)

**Comment by bajras** [comment]
That worked but now when I install the fonts, theres too much letter spacing between characters. 

![screen shot 2017-10-04 at 12 15 02 pm](https://user-images.githubusercontent.com/3359989/31189399-c2a535fa-a8fd-11e7-94fb-33d5c407d666.png)
 
![screen shot 2017-10-04 at 12 13 05 pm](https://user-images.githubusercontent.com/3359989/31189317-7dea029c-a8fd-11e7-9d0f-e3cca1a39fdc.png)

**Comment by kiliman** [comment]
Somebody had a similar issue, but it was his original font that was messed up. See #13 

Can you email me privately kiliman@gmail.com and I'll see what I can do?

Thanks!

**Comment by bajras** [comment]
Can we talk about it here? That way it will help others who might have the same issue.

**Comment by kiliman** [comment]
Ok, there have been 100+ people that have not had issues. The only one other than you had a messed up source font.

I need you to send me the original font so I can try to reproduce the error.

**Comment by kiliman** [comment]
I think I see the problem. You were trying to patch the non-Mono version. Yeah, these ligatures only work on the Operator Mono fonts.

![image](https://user-images.githubusercontent.com/47168/31203124-ac02b224-a933-11e7-96e0-ac3b1afc78c6.png)

**Comment by bajras** [comment]
Ok I will try with the Mono again. Thanks for the help.
