### ISSUE TITLE
`/ligature/OperatorMonoLig-Book{,Italic}` - missing `charstrings.xml` in folders

### ISSUE THREAD

**Issue by evandrix** [kiliman/operator-mono-lig#20]
This causes the included `build.sh` to fail on these 2 fonts.

Is it because they are not supported?

**Comment by kiliman** [comment]
Odd. `build.sh` has the following lines to check for `charstrings.xml'

```bash
    if [ ! -e "./ligature/$lig/charstrings.xml" ] 
    then 
        return 
    fi
```

Can you confirm you have the latest?

Thanks!

**Comment by kiliman** [comment]
If this is still an issue, let me know and I'll re-open.
