### ISSUE TITLE
What do you mean by Mono SSm Versions?

### ISSUE THREAD

**Issue by clstudio** [kiliman/operator-mono-lig#21]
Your project is a godsend, thank you!

I'm sorry but I only have `Operator SSm` (not mono) and `Operator Mono` (not SSm).

When I compile nothing works except `OperatorMonoLig-Medium.otf`and `OperatorMonoLig-MediumItalic.otf`

What `Operator Mono SSm` are you talking about? It's not [here](https://www.typography.com/fonts/operator/styles/).

**Comment by kiliman** [comment]
SSm are the ScreenSmart versions. I originally had the regular version and did the Medium weight font. Someone told me that the ScreenSmart versions were much nicer. I checked them out and agreed. 

I plan on doing all the weights for both versions. It's just a matter of finding the time. 

https://www.typography.com/fonts/operator/styles/screensmart/

**Comment by clstudio** [comment]
Allright, now I know what you mean, thanks a lot!
