### ISSUE TITLE
'ttx' is not recognized 

### ISSUE THREAD

**Issue by NicolaSansom** [kiliman/operator-mono-lig#22]
Hi there,

When I run the build command I get the following error when building the fonts:

`'ttx' is not recognized as an internal or external command, operable program or batch file.`

Any idea how to resolve this?

**Comment by kiliman** [comment]
I'm assuming you already installed Python and FontTools from README.

If `ttx` is not found, then most likely it didn't end up in your PATH.

Which OS are you using?

**Comment by kiliman** [comment]
Check issue #6 

That person had a similar issue.

**Comment by NicolaSansom** [comment]
Thanks and I worked though the comments and using `pip2 install fonttools` instead of `pip install fonttools` seemed to resolve the issue for me on OS. The only issue I have now is that it is only creating the Medium font-weight and missing out the others.

**Comment by NicolaSansom** [comment]
Nevermind just deleted some files out of the folder and it worked thanks for your help!

**Comment by reslear** [comment]
if you have error `ttx: command not found` 
use: `brew install fonttools`

**Comment by thienbao12a2** [comment]
> if you have error `ttx: command not found` use: `brew install fonttools`

This works for me. Thank you
