### ISSUE TITLE
[Request] Operator Mono Book

### ISSUE THREAD

**Issue by ukaric** [kiliman/operator-mono-lig#23]
Hi any chance of patching Operator Mono Book non SSm version ?

**Comment by mgsmus** [comment]
I also need regular book version. Medium version (with or without ligatures) is not looking good in PhpStorm on Windows.

**Comment by ukaric** [comment]
@mgsmus I think that it supports OperatorMono-Book.otf and Italics version non SSm version, I have managed to patch those fonts, but most of the ligatures are missing here is snap of Vscode running on Windows.

![2017-10-13](https://user-images.githubusercontent.com/9012882/31553558-2b5b205c-b03b-11e7-8cc1-99d6cb63937e.png)

**Comment by kiliman** [comment]
Sorry for the delay in the non-ScreenSmart versions. I've been pretty swamped with work and family life.

Anyway, it takes about 30-45 minutes to do each weight. Plus doing the italic version as well.

I will try to get these done on Sunday.

**Comment by scheMeZa** [comment]
You're awesome! :)

**Comment by kiliman** [comment]
I've added Operator Mono Book. Still need to do italic.

Let me know what you think.

**Comment by kiliman** [comment]
Ok, finished Operator Mono Book Italic

![image](https://user-images.githubusercontent.com/47168/31627827-a00bfe7e-b27c-11e7-8021-15372fb32041.png)

**Comment by CarlosRGL** [comment]
you are awesome, thx dude
