### ISSUE TITLE
Operator Mono Book Italic has wrong family name and subfamily

### ISSUE THREAD

**Issue by feilb** [kiliman/operator-mono-lig#24]
When generating your new Operator Mono Book Lig Italic, the font name is set to "Operator Mono Book Lig Italic" and subfamily is set to "Regular".

These values should be set to "Operator Mono Book Lig" and "Italic" respectively.

Without this change the italic font is seen as a separate font family and not a style of Operator Mono Book Lig.

**Comment by kiliman** [comment]
Thanks. This has been fixed.
