### ISSUE TITLE
Request <=> and ?? ligatures

### ISSUE THREAD

**Issue by Orillian** [kiliman/operator-mono-lig#25]
Can I add to this by putting in a request for the following for PHP.
Null coalescing operator ?? 
and 
Spaceship operator <=> <----this one more, as the current <= ligature causes this one to look especially bad! 

![ligatures_needed](https://user-images.githubusercontent.com/823192/32059996-d6315e94-ba2a-11e7-8f5a-2d7ca7e86e74.png)

**Comment by Orillian** [comment]
![spaceship and null co](https://user-images.githubusercontent.com/823192/35844873-f3d4c95c-0acc-11e8-8ed6-bea96d60b415.png)

Here I made the glyphs touch, it seemed more fitting.

**Comment by kiliman** [comment]
These look cool, but remember, the ligatures have to take the same amount of space that the original characters would. So the <=> should take 3 characters width.

**Comment by Orillian** [comment]
Ah, is there a way to center these? If not are we able to stretch the central `=` to fill the gap? almost an `<==>`?

**Comment by kiliman** [comment]
Yeah, this is how it would look.

![image](https://user-images.githubusercontent.com/47168/35883371-0e9e62a6-0b55-11e8-857c-c1f601cad217.png)

**Comment by kiliman** [comment]
I'm redoing all the ligatures based on the new process. Here's what it currently looks like. I've includes some new ligatures as well.

![image](https://user-images.githubusercontent.com/47168/36906928-360baad4-1e05-11e8-8b91-0cbc77a93a06.png)

**Comment by Orillian** [comment]
I like it so far!

**Comment by kiliman** [comment]
The ligatures have been included in the new branch features/contextsubst.

NOTE: This only includes the Operator Mono ScreenSmart Book and Book Italic versions. This update was mainly for testing the new build process.
