### ISSUE TITLE
No output from build

### ISSUE THREAD

**Issue by bjrnt** [kiliman/operator-mono-lig#26]
Hello,

I can't seem to get the build step to work. Is there anything I'm missing here?

I'm on OS X 10.12.

```
operator-mono-lig/original git/master
❯ ls
Operator Mono Bold Italic.otf    Operator SSm Black Regular.otf
Operator Mono Bold Regular.otf   Operator SSm Bold Italic.otf
Operator Mono Book Italic.otf    Operator SSm Bold Regular.otf
Operator Mono Book Regular.otf   Operator SSm Book Italic.otf
Operator Mono Light Italic.otf   Operator SSm Book Regular.otf
Operator Mono Light Regular.otf  Operator SSm Light Italic.otf
Operator Mono Medium Italic.otf  Operator SSm Light Regular.otf
Operator Mono Medium Regular.otf Operator SSm Medium Italic.otf
Operator Mono XLight Italic.otf  Operator SSm Medium Regular.otf
Operator Mono XLight Regular.otf Operator SSm XLight Italic.otf
Operator SSm Black Italic.otf    Operator SSm XLight Regular.otf
```

```
❯ node -v
v8.4.0
```

```
❯ yarn
yarn install v1.2.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.14s.
```

```
❯ python --version
Python 2.7.12
```

```
❯ pip install fonttools
Requirement already satisfied (use --upgrade to upgrade): fonttools in /usr/local/lib/python2.7/site-packages
```

Running the build script doesn't produce any kind of output at all.

Thanks!

**Comment by kiliman** [comment]
Hmm.. the filenames for the fonts are different than what I have and the script is expecting. There should be no spaces in the filename.

I'll need to update the script to handle both, but in the meantime, remove the spaces and also get rid of the work Regular. That should fix the problem.

Thanks!

![image](https://user-images.githubusercontent.com/47168/32106505-e3c2de1e-baf9-11e7-9cb5-ddf938e14b82.png)

**Comment by bjrnt** [comment]
Thank you! 
I did a quick rename as follows:
```bash
for f in *; do mv "$f" "${f// /}"; done # remove spaces
for f in *; do mv "$f" "${f//no/no-}"; done # add dash after Mono
for f in *; do mv "$f" "${f//Regular/}"; done # remove Regular
```
After that the build succeeded.

Thank you for the awesome tool - enjoying the ligatures a lot! :)

**Comment by Zed-M** [comment]
i had this issue all day this is so overwhelming :(

**Comment by kiliman** [comment]
@Zed-M can you send me the output? Also what is in the ./original folder?

**Comment by FakeDazon** [comment]
I have an issue similar to this.
![image](https://user-images.githubusercontent.com/44048306/77562466-4a048900-6e7d-11ea-8b49-0107a0f34cb9.png)
This is what outputs for every font it tries. 
![image](https://user-images.githubusercontent.com/44048306/77562569-6a344800-6e7d-11ea-995a-ccae32cc40fa.png)
here is my ./original folder.

**Comment by kiliman** [comment]
@FakeDazon apparently the script is not running the `ttx` command on the original font files. What happens when you type `ttx` on the command line?

`ttx` is used to convert `.otf` files to `.ttx` (XML) so the tool can add the ligatures. Then it uses the command to convert it back to an `.otf` file. So if `ttx` is not in the path, the tool will not be able to do anything.

**Comment by FakeDazon** [comment]
![image](https://user-images.githubusercontent.com/44048306/77568619-209c2b00-6e86-11ea-985d-6be07ab1b1e6.png)
this happens

**Comment by kiliman** [comment]
Did you make sure you installed `fonttools`? It's one of the prerequisites.

You need to install Python, then install `fonttools` using `pip/pip3`. See the README.

**Comment by FakeDazon** [comment]
i installed both i believe

**Comment by FakeDazon** [comment]
![image](https://user-images.githubusercontent.com/44048306/77571665-f305b080-6e8a-11ea-9dfc-76890ff7242c.png)
yeah here i installed it. i attempted building it right after, and it didnt work

**Comment by kiliman** [comment]
If you look at the WARNING, you'll see that the fonttools folder is not in the PATH.

![image](https://user-images.githubusercontent.com/47168/77575021-4129ac80-6ea9-11ea-8f6e-f213340e7e24.png)

Make sure you add that folder to the PATH. Then close and reopen the command prompt.

**Comment by FakeDazon** [comment]
It worked, the otf files are in the build folder. Thanks!
