### ISSUE TITLE
Thank you :)

### ISSUE THREAD

**Issue by kmaida** [kiliman/operator-mono-lig#28]
As a note, I had to do an extra step (use `ttx` to convert the original .otf files to .ttx before running `build`), so it might be nice to add this to the README.

But mostly I just wanted to say thank you for doing this!! :) The ligatures look great.

**Comment by kiliman** [comment]
Hmm.. that's odd. The build.bat/build.sh script should have generated the .ttx files automatically.

Anyway, glad you like it.

**Comment by kmaida** [comment]
The build.sh script produced errors saying the .ttx files couldn't be found until I generated them manually with fonttools (Mac OSX Sierra, latest fonttools, Python 2.7, Node 8.9.1).
