### ISSUE TITLE
Glyph not added.

### ISSUE THREAD

**Issue by br0gr4mmer** [kiliman/operator-mono-lig#33]
Glyphs are not added to my font files, doesn't render in my Illustrator Glyphs panel.

Could be related to this error: `WARNING: GSUB/GPOS Coverage is not sorted by glyph ids`?

**Comment by kiliman** [comment]
Hmm.. I tried in Illustrator and I see the glyphs. Scroll all the way to the bottom.

NOTE: You don't need to add they glyphs from the panel. You can simply type the characters and the ligatures will automatically appear.

![image](https://user-images.githubusercontent.com/47168/33806531-94259f34-dd97-11e7-92e3-5cee3f00985a.png)
