### ISSUE TITLE
Add Haskell bind operators >>= and =<<

### ISSUE THREAD

**Issue by andy1li** [kiliman/operator-mono-lig#36]
Hi Killman and friends,

Really appreciate your effort of bringing ligatures to Operator Mono!

If possible, would you kindly add support for the Haskell bind (`>>=`) and reverse bind (`=<<`) operators?

Currently `>>=` would be rendered as `>≥`, which is sort of weird.

Although `=<<` works fine, it might be nice to add it too, for the sake of symmetry if `>>=` could be fixed.

Thank you so much and happy holidays!

**Comment by kiliman** [comment]
Thanks. I have some time off during the Christmas break. I'm going to work on cleaning up and adding additional ligatures.

**Comment by kiliman** [comment]
Ugh. Sorry, as you can tell I wasn't able to find the free time to work on the ligatures. We had 14 people at the house for Christmas. As you can imagine, it was quite crazy around here.

**Comment by andy1li** [comment]
No worries and thanks for the update~

Still immensely appreciating what you have already put out for the public to use for free. Anything more would seem like impositions, which means we issue openers are the ones should apologize to you instead.

**Comment by kiliman** [comment]
These ligatures have been pushed to new branch features/contextsubst

NOTE: I only have the Operator Mono SSm Book and Book Italic fonts. This update was mainly to test the new build process.

![image](https://user-images.githubusercontent.com/47168/39335477-3c6dc586-4981-11e8-82a0-f1950319b04b.png)

**Comment by andy1li** [comment]
Fantastic!

<img width="838" alt="screen shot 2018-04-27 at 07 05 27" src="https://user-images.githubusercontent.com/1450947/39336435-1b3ef7ae-49ea-11e8-9430-b8077eadd11d.png">
