### ISSUE TITLE
ERROR: File not found: "build/OperatorMonoLig-MediumItalic.ttx"

### ISSUE THREAD

**Issue by aditya2337** [kiliman/operator-mono-lig#4]
This error comes up when I do `./build.sh` from my linux

**Comment by kiliman** [comment]
Did you add OperatorMono-MediumItalic.otf to your ./original folder? It can't build the ligature version without the original. There's not a lot of error checking in the scripts, so something must have failed during the process. That was just the last step.

Can you send me all the output? 

Thanks!

**Comment by AlexVernon** [comment]
I am receiving the same message on Windows. After the **npm install** command I also receive this error. 

> npm WARN operator-mono-lig@1.0.0 No repository field. 

Here is the output of my build command.

[https://gist.github.com/AlexVernon/415f504f8a19284062f9a52115f27ba3](url)

**Comment by kiliman** [comment]
Ah. Apparently you are using an older version of Node.js. I'm on v7.7.4 which supports `async/await`. Apparently you need to be on at least v7.6.

Can you update then see if that works? I will update the README.

```
C:\dev\GitHub\operator-mono-lig\index.js:16
async function main() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
```

**Comment by AlexVernon** [comment]
I upgraded Node.js to version 8.4.0 and now it works. Thank you very much.
