### ISSUE TITLE
Build does not generate fonts on Windows and macOS

### ISSUE THREAD

**Issue by marekkaczkowski** [kiliman/operator-mono-lig#41]
Hey,
trying to build lig version of operator mono with your scripts:

1. OTF files are in ./original dir (no sub-dirs),
2. fonttools are installed @3.21.2,
3. node @9.5.x,
4. npm install ok,
5. running build just creates empty build dir :( no errors, warnings...

```
~/Downloads/operator-mono-lig-master  ttx --version
3.21.2
 ~/Downloads/operator-mono-lig-master  node --version
v9.5.0
 ~/Downloads/operator-mono-lig-master  ./build.sh
 ~/Downloads/operator-mono-lig-master 
```
Same on Windows :(

**Comment by kiliman** [comment]
What are the filenames? I notice that some people have files with spaces. The script expects them to have no spaces.

See #26

**Comment by marekkaczkowski** [comment]
That was an issue!
So name should not contain spaces, contain dash between font name and variant and no `Regular` in name like:
`OperatorMono-MediumItalic`
