### ISSUE TITLE
repository not found

### ISSUE THREAD

**Issue by jinze1991** [kiliman/operator-mono-lig#43]
npm WARN operator-mono-lig@1.0.0 No repository field.

![from_tk kim 2018-02-08 at 15 21 09](https://user-images.githubusercontent.com/6781906/35958356-b9d31916-0ce3-11e8-8a79-610c7b5c7d6e.png)

**Comment by jinze1991** [comment]
I successfully produced a new font, and I think I did not succeed before because node version is too low, updated to v9.5.0 on the success. thank you very much. Let me have a very attractive font.

**Comment by kiliman** [comment]
Thanks! I'm glad you like it.

**Comment by rolandleth** [comment]
@kiliman Hey, I'm having this issue as well. Running node `9.6.1`.

**Comment by kiliman** [comment]
@rolandleth what error message are you getting?

Thanks!

**Comment by rolandleth** [comment]
@kiliman Just like in the screenshot above.

**Comment by kiliman** [comment]
@rolandleth That appears to be a simple warning. Have you tried running `./build.sh`?

**Comment by rolandleth** [comment]
@kiliman I did, but nothing happens. If I check `node_modules`, the package that raises the error isn’t installed.

**Comment by rolandleth** [comment]
@kiliman Well ... This is weird. I tried `.build/sh` again and it worked 🤷🏻‍♂️

Thanks for your help and also for all your effort on this project!

**Comment by kiliman** [comment]
Hmm. That is strange. Anyway, glad you got it working. I'm in the process of re-doing all the ligatures and adding new ones, so keep an eye out for the update.

Thanks!
