### ISSUE TITLE
build.sh does not work in zsh, but in bash

### ISSUE THREAD

**Issue by tbsvttr** [kiliman/operator-mono-lig#47]
When I started the build.sh in zsh it only changed directory to /build, but it did nothing else. When I started bash (even from zsh) and started build.sh again everything worked.

**Comment by kiliman** [comment]
I'm not a bash or zsh expert. I'm lucky I got the current script working as is 😅.

Do you see anything glaringly obvious as to why it's not working? Basically I just wanted to add some checks to see if there was a valid build for each font before processing. Any help would be appreciated.

Thanks!

**Comment by peteplays** [comment]
I am having the same issue

**Comment by kiliman** [comment]
Hm... not sure why you're getting the errors. It's working here for me.

As you can see, I switched to the `zsh` shell. Are you getting any error messages?

![image](https://user-images.githubusercontent.com/47168/36562711-ccd26564-17e5-11e8-90b1-038e6098d822.png)

**Comment by kiliman** [comment]
Have you tried running `ttx` or `node` from the command prompt?

**Comment by dinophile** [comment]
Also having the same issue. Running the ./build.sh command creates a build folder but nothing happens. No error messages...just back to a blank line after.

**Comment by kiliman** [comment]
@dinophile that sounds more like your font files have the wrong filenames. See #26.

**Comment by dinophile** [comment]
@kiliman Ah right...thank you for pointing that out! Will try again when I get back to my keyboard!
