### ISSUE TITLE
Adding |> <| support (For Elm especially)

### ISSUE THREAD

**Issue by BeardedBear** [kiliman/operator-mono-lig#5]
|> or <| in Elm is ugly
Love the triangles with Fira Code !
![image](https://user-images.githubusercontent.com/7188702/29814540-043613fc-8cae-11e7-9098-54d7e6e4432c.png)

**Comment by kiliman** [comment]
I've started on the glyphs. What do you think?

![image](https://user-images.githubusercontent.com/47168/30181431-39700fca-93e1-11e7-8417-06aca526ec49.png)

**Comment by BeardedBear** [comment]
I love it ! :D

**Comment by kiliman** [comment]
Here's the other... I fixed the spacing to be more "optically" centered vs "numerically" centered.
![image](https://user-images.githubusercontent.com/47168/30182902-77ab15a0-93e6-11e7-91c5-b6b53de97abc.png)

**Comment by BeardedBear** [comment]
Love it too ! Very good job !

**Comment by kiliman** [comment]
Closed by 2464f9f94100d1fb86718f529d3aa2bb20b0e1fd

Used wrong issue #.
