### ISSUE TITLE
Failed with ttx command not found error

### ISSUE THREAD

**Issue by smlombardi** [kiliman/operator-mono-lig#50]
Running on High Sierra with Python 2.7.10:

```
Building OperatorMonoSSmLig-Book
./build.sh: line 19: ttx: command not found
/Users/st016lo/Downloads/operator-mono-lig-master/index.js:20
async function main() {
      ^^^^^^^^
```

Fonttools is installed.

**Comment by smlombardi** [comment]
Node v6.11.2
Python 2.7.10
-bash: ttx: command not found

fontTools is apparently installed in `/Library/Python/2.7/site-packages` and I see `ttx` in there.

**Comment by kiliman** [comment]
You need node 7.6+ for async/await support.

Hmm... I'm not an expert on Python on the Mac. Your paths are different... mine is located in /usr/local/lib/python2.7/site-packages and all the python tools are symlinked to /usr/local/bin which is in my $PATH.

I understand other people had better luck doing:

brew install python
pip3 install fonttools

**Comment by smlombardi** [comment]
i updated Node (i use NVM) to 9.9.0 and everything works now.  Thanks.
