### ISSUE TITLE
Running ./build.sh does nothing

### ISSUE THREAD

**Issue by JamesTheHacker** [kiliman/operator-mono-lig#52]
I'm running OSX 10.12.6

I've followed the prerequisites and have `fonttools` installed. After I cloned the repo I copied the Operator Mono fonts to original directory and ran `./build.sh`. It runs very quickly and produces no output.

I checked the 'build' directory and it's empty. Any ideas?

**Comment by kiliman** [comment]
The tool only processes fonts that it has the ligatures for. It also looks for the filenames in ./original with a specific format.

The filenames should look like this:

![image](https://user-images.githubusercontent.com/47168/38698956-ba506fee-3e64-11e8-98af-234017deac57.png)

**Comment by kiliman** [comment]
Please re-open if you're still having the issue

**Comment by JamesTheHacker** [comment]
Sorry for the delay in responding. I solved it in the end. I had my filenames wrong from when I backed up.
