### ISSUE TITLE
Request: </ and /> ligatures for HTML tags.

### ISSUE THREAD

**Issue by bradstewart** [kiliman/operator-mono-lig#53]
Fira code has these, and I find they make reading HTML much easier.

![screenshot from 2018-04-19 12-18-13](https://user-images.githubusercontent.com/3613191/39007583-c1d5a54c-43cb-11e8-9768-f9b917887518.png)

Also, thanks for your work on this project. It is very much appreciated.

**Comment by kiliman** [comment]
Yeah, I've actually redone all the ligatures and added a few more. It also supports more advanced OpenType features so it works more like Fira Code. I've just been so busy, I haven't had time to finish and update the docs.

**Comment by bradstewart** [comment]
Awesome. If I knew literally anything about fonts, I'd offer to help. Maybe I'll fiddle around with Glyphs this weekend, it seems pretty interesting.

**Comment by kiliman** [comment]
Here's work in progress:
![image](https://user-images.githubusercontent.com/47168/39058270-593a8cdc-4489-11e8-8349-15e7971757b4.png)
![image](https://user-images.githubusercontent.com/47168/39058420-c36e0f70-4489-11e8-9d9c-b087e56fa9f1.png)

**Comment by kiliman** [comment]
Done in 3ac6faed0c71802aa9887bc0c70f15496031df8c
