### ISSUE TITLE
Add support for powerline patching

### ISSUE THREAD

**Issue by MrLoh** [kiliman/operator-mono-lig#56]
This is such an awesome project. I love it.

Would you consider including code to patch in powerline symbols. There are already some approaches available. 
https://github.com/emanuelhouse/fontpatcher/tree/operator-mono

**Comment by MrLoh** [comment]
Awesome and those are much nicer icons than the standard ones. Looking forward to it.

Btw. what do you think about naming the resulting font Operator Code, just a random thought.

**Comment by kiliman** [comment]
As for Operator Code... I probably won't. I'm already skirting the line on acceptable use of the licensed font. Changing the name would make it seem like I'm creating a derivative work, whereas the tool is simply enhancing your existing font. I only add the Lig suffix so you can still use the original font side-by-side.

**Comment by Sawtaytoes** [comment]
Has powerline support been added?

**Comment by kiliman** [comment]
Sorry, work has keep me super busy the past few months, so haven't had a chance to really work on it.

**Comment by kiliman** [comment]
I've added initial glyphs for Powerline support. It looks really nice.

![image](https://user-images.githubusercontent.com/47168/56161905-ba7e0700-5f98-11e9-804a-9e488e5f44eb.png)

I've used a nicer "branch" glyph.

![image](https://user-images.githubusercontent.com/47168/56162143-4b54e280-5f99-11e9-9256-00ac9c7b4356.png)

**Comment by kiliman** [comment]
Not yet. I had to make changes to the extract and build process since these are not technically ligatures but simple glyphs. I hope to post some updates over the next few days.

**Comment by kiliman** [comment]
Done in 40b6425f413edec6f346879ba6db278b2920f256

**Comment by kiliman** [comment]
@MrLoh I've committed to the `features/contextsubst` branch. However, note that this branch currently only has support for Operator Mono SSm Book (and partial for Light).

Once I finish re-doing all the other ligatures, I'll merge this branch into master.
