### ISSUE TITLE
Ligatures not showing in VS Code

### ISSUE THREAD

**Issue by vishiri** [kiliman/operator-mono-lig#72]
Hello, 

I successfully followed your tutorial on how to generate ligatures from the fonts, but when I installed them and finally got them running in VScode, the ligatures don't show at all. There is only blank, empty space instead of the ligature.

Any idea why?

config:
```json   
   "editor.fontFamily": "Operator Mono Lig",
   "editor.fontWeight": "400",
   "editor.fontLigatures": true,
```

**Comment by kiliman** [comment]
Sorry. That's a new one. Are you on macOS or Windows?

Have you tried any other apps?

**Comment by Elvanos** [comment]
I am on windows and no, I have not tried other apps. Any suggestions on where to test it at?

**Comment by Orlmente** [comment]
You can try it in SublimeText, working for me so far... in setting just drop the font name with weight too:
`"font_face": "Operator Mono Lig Book",`

**Comment by marichelle** [comment]
This doesn't work for me in VSCode either. I'm on MacOS v10.14.2.

**Comment by kiliman** [comment]
Here's what I'm using (the `@sync` keyword is used by Sync Settings extension):

```json
"editor.formatOnSave": true,
  //@sync os=mac
  "editor.fontFamily": "OperatorMonoSSmLig-Book",
  //@sync os=windows
  //"editor.fontFamily": "Operator Mono SSm Lig",
  "editor.fontLigatures": true,
  "editor.fontSize": 17,
  "editor.fontWeight": "300",
  "editor.lineHeight": 25,
  "editor.letterSpacing": 0.5,
  ```

**Comment by ermik** [comment]
Ligatures did show for me, but triple-equal only shows if you add a 4th `=` sign — `(===)=` — the bracketed portion becomes a ligature. `:=` doesn't detect a ligature at all. Hopefully that helps?

**Comment by jinoantony** [comment]
Works for me in VS Code after reloading the editor.
