### ISSUE TITLE
Didn't work. You know what this error means? 

### ISSUE THREAD

**Issue by EdgeCastMedia** [kiliman/operator-mono-lig#74]
![not-working](https://user-images.githubusercontent.com/39596436/45440452-4853e580-b68a-11e8-9569-823eb1e0b860.png)

Plese help. I'd love for it to actually work. Thanks for your help .

**Comment by kiliman** [comment]
The error `ttx: command not found` means the script can't find the `ttx` command that is part of `fonttools`.

Which version of Python do you have installed? Type `python -V` in your shell.

For Python 3+, use `pip3 install fonttools` otherwise use `pip install fonttools`

**Comment by kiliman** [comment]
To make sure you have `ttx` succesfully installed, type: `ttx --version` in you shell.

![image](https://user-images.githubusercontent.com/47168/45441970-ac78a880-b68e-11e8-8e3c-3cd934cde8bd.png)

**Comment by EdgeCastMedia** [comment]
It doesn't look like it's installed. I tried ti install it and didn't have
any luck. I'm not sure what ttx is. Looked it up and there's not any
information about it? How do I go about this. I've been trying to get this
to work all day :(

[image: ttx.png]


Thanks,




*Travis Ealy*

*Founder/Developer*EdgeCast Media
P: 954 243-5119
W: www.edgecastmedia.com

**Comment by EdgeCastMedia** [comment]
Python 2.7.10

**Comment by EdgeCastMedia** [comment]
Hey Buddy. Its was the pip3 that I was missing. I got it! Amazing work man. Thanks again!!
