### ISSUE TITLE
Weird width using Operator Mono PRO

### ISSUE THREAD

**Issue by JiggyJinjo** [kiliman/operator-mono-lig#75]
https://github.com/kiliman/operator-mono-lig/issues/14#issue-258644833
When using the pro version of Operator Mono, the compiled Lig font is broken : the width is way too large. I tried with your new branch and it's even worse as the letters aren't displayed at all. Can you fix please ?

Version used : 1.200 **Pro**

Version 1.200 works well

**Comment by Sawtaytoes** [comment]
As far as I've seen, there's no Operator Mono with a Pro designation.

See here:
https://www.typography.com/fonts/operator/styles/

**Comment by kiliman** [comment]
@JiggyJinjo are you sure it's not plain Operator (variable-width)? The only "Pro" reference I see is for the Operator Pro collection (it contains more weights and styles).

![image](https://user-images.githubusercontent.com/47168/47651608-17f0d980-db5a-11e8-854c-cafa719c46f2.png)

**Comment by JiggyJinjo** [comment]
@kiliman yes it is. Is it not working because of the name being different ?
![alt text](https://i.imgur.com/GGSb9UH.png "Operator Mono")

**Comment by kiliman** [comment]
Your font name is Operator SSm Book, not Operator Mono. Mono is monospaced (fixed-width). You're using the variable width version which most likely will not work with the ligatures.

**Comment by JiggyJinjo** [comment]
Sorry I mixed up the name of the font, I was referring to Operato SSm Book all along.
I did try by renaming the font to OperatorMonoSSmLig-Book. It does work with the v1.200 version but it doesn't with this Pro one. I tried with my friend's non-pro version and it works well with (Operator SSm Book v1.200). Do you actually support theses or it was pure luck it worked ? I'll try redownloading the latest known version on H&C and retry.
