### ISSUE TITLE
Issue with Mac Mojave

### ISSUE THREAD

**Issue by tuetran-agilityio** [kiliman/operator-mono-lig#76]
I just updated MacOS form Siera to Mojave. And when run ./build.sh, it give error ttx:command not found. I've installed Font tools. Could you please help check with Mojave. Thanks

**Comment by kiliman** [comment]
Where is `ttx` installed? It needs to be on the PATH

![image](https://user-images.githubusercontent.com/47168/48143410-bd9ff900-e27c-11e8-9fad-4529117bd22e.png)
