### ISSUE TITLE
Is this the correct output?

### ISSUE THREAD

**Issue by LynyrdRoss** [kiliman/operator-mono-lig#80]
Put my OperatorMono-Book.otf in original folder

After doing a build:

Building OperatorMonoLig-Book
Dumping "./original/OperatorMono-Book.otf" to "./original\OperatorMono-Book.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
Dumping 'DSIG' table...
Reading original font file ./original/OperatorMono-Book.ttx
Patching names
Patching glyphs
Patching gpos
Patching gsub
Patching hmtx
Patching charstrings
Writing ligature font file ./build/OperatorMonoLig-Book.ttx
Done
Compiling "./build/OperatorMonoLig-Book.ttx" to "./build\OperatorMonoLig-Book.otf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'name' table...
Parsing 'cmap' table...
Parsing 'post' table...
Parsing 'CFF ' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Parsing 'hmtx' table...
Parsing 'DSIG' table...
WARNING: GSUB/GPOS Coverage is not sorted by glyph ids.

I got a OperatorMono-Book.ttx, is this the right thing? how do I use this in VC Code?

**Comment by kiliman** [comment]
Look in the build folder for the OperatorMonoLig-Book.otf file. Then install it like you would any other font.

**Comment by LynyrdRoss** [comment]
I did install it, I also tried Book/BookItalic/Medium/MediumItalic all types but when I use it in VS code via settings.json via "editor.fontFamily": "Operator Mono". Operator mono works but no Ligature.

**Comment by kiliman** [comment]
Here are the settings I use.

  //@sync os=mac
  "editor.fontFamily": "OperatorMonoSSmLig-Book",
  //@sync os=windows
  "editor.fontFamily": "Operator Mono SSm Lig",
  "editor.fontLigatures": true,
  "editor.fontSize": 17,
  "editor.fontWeight": "300",
  "editor.lineHeight": 25,

The sync keys are for syncing settings for Mac and Windows.

Make sure you have the fontLigatures setting set to true.

**Comment by LynyrdRoss** [comment]
Before modding the Operator Mono SSm Lig, what is its original OTF name?

**Comment by kiliman** [comment]
SSm is for the ScreenSmart version. Just remove SSm from the name if you are using the regular version.

**Comment by LynyrdRoss** [comment]
I have modified using your package and installed all OperatorMono-[Book/BookItalic/Medium/MediumItalic] versions. then in my VSCode settings.json:

"editor.fontFamily": "Operator Mono",
"editor.fontLigatures": true,
"editor.fontSize": 16

Operator mono works but still no ligature.

**Comment by kiliman** [comment]
The whole purpose of this project is to take your original font and generate new fonts with ligatures. They are in the build folder. I also add Lig to the name so you can install it along with the original fonts.

If you don't use the Lig name, then you will just see the original fonts without ligatures.

Do you see the Lig versions in the installed fonts list (control panel for Windows, Font Book for macos)?

**Comment by LynyrdRoss** [comment]
I got it to work thanks, maybe I am just installing the wrong font. But it works now. For some reason, "editor.fontFamily": "Operator Mono Lig Medium" works but "editor.fontFamily": "Operator Mono Lig Book" does not even though I generated and installed both font types.

**Comment by kiliman** [comment]
Try setting font-family to Operator Mono Lig, then set fontWeight to:

100 - Thin
200 - Extra Light, Ultra Light
300 - Light
400 - Normal, Book, Regular
500 - Medium
600 - Semi Bold, Demi Bold
700 - Bold
800 - Extra Bold, Ultra Bold
900 - Black, Heavy

**Comment by LynyrdRoss** [comment]
I have done it correctly thanks for the suggestion. I would like to ask if the <=> spaceship supported in your Package? Doesn't seem to work, other than that, it goes perfect. :)
