### ISSUE TITLE
Font opacity

### ISSUE THREAD

**Issue by silencerspirit** [kiliman/operator-mono-lig#83]
Hello guys! Tell me please why font changed opacity after generate 
![image](https://user-images.githubusercontent.com/22055696/58494609-277ee200-817e-11e9-9798-6ef2fc0e5a1e.png)
The opacity of the ligatures is OK, but the opacity of the rest of the font has become less than 1
Where problem? thanks

**Comment by kiliman** [comment]
Sorry for not responding earlier. All the ligatures are custom designed for each font weight. That is, there are different glyphs for Light vs Book vs Medium. Also I have different glyphs for ScreenSmart vs regular fonts.

Can you tell me which font you are trying to use?

**Comment by silencerspirit** [comment]
Hi, thanks for the feedback. I used SSm Light Regular and opacity are OK)
