### ISSUE TITLE
Add := ligature

### ISSUE THREAD

**Issue by hhquerybuilder** [kiliman/operator-mono-lig#90]
This is heavily used in golang and it looks a bit off:
![image](https://user-images.githubusercontent.com/40240395/61446147-64ce4780-a957-11e9-9247-a8d646fbd67a.png)

Fira Code example:
![image](https://user-images.githubusercontent.com/40240395/61446497-e7ef9d80-a957-11e9-8649-03c16cf59e67.png)

**Comment by kiliman** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/47168/61481381-2c823580-a966-11e9-886d-4464cbb11d57.png)

When I create my ligatures, I actually use the existing Operator Mono glyphs. So the same square colon and beveled equal sign.

**Comment by hhquerybuilder** [comment]
This looks great in my opinion.
I want to say a big Thank You for all of your work and for making Operator Mono look better and better.

**Comment by kiliman** [comment]
Are you using Operator Mono SSm Book? Currently that's the only one I've got all the new ligatures in (on the `features/context-subst` branch). I rewrote the way the font is generated and haven't had a chance to redo all the other weights.

If so, I'll try and get this glyph pushed this weekend. Otherwise, you'll need to wait until I get the other weights redone.

**Comment by hhquerybuilder** [comment]
I do use SSm Book. Thanks again.

**Comment by dorudumitru** [comment]
Waiting on this as well.

**Comment by kiliman** [comment]
Here's the new ligature in VS Code. I even show an alternate <= ligature.

![image](https://user-images.githubusercontent.com/47168/61742628-908b6c00-ad61-11e9-9ae6-da0a1043967a.png)

**Comment by kiliman** [comment]
Closed by 2de4cec227ea2971ebefd8665ad2d9792eb7d5d0

**Comment by kiliman** [comment]
Please use the `develop` branch. I've merged the feature branch and deleted it.
