### ISSUE TITLE
Unable to install the ligature

### ISSUE THREAD

**Issue by Vaibbhav26** [kiliman/operator-mono-lig#91]
Windows isn't able to recognize the "build" command which is supposed to create the OTF files. I am doing something wrong?

**Comment by kiliman** [comment]
The "build" command is a batch file. It runs the `node index.js` command. Are you in the root directory of the project? What error are you getting?

**Comment by kiliman** [comment]
I'm closing this issue. You can reopen if you're still having a problem. Thanks!
