### ISSUE TITLE
Looking forward to the Light version

### ISSUE THREAD

**Issue by urielzen** [kiliman/operator-mono-lig#92]
Is Light supported in any version? 1 or 2?

**Comment by kiliman** [comment]
Actually v2 does have partial support for Operator Mono Light.

https://github.com/kiliman/operator-mono-lig/tree/master/ligature/OperatorMonoLig-Light/glyphs

![image](https://user-images.githubusercontent.com/47168/62078497-c1184d80-b21a-11e9-9bff-cef4862df388.png)

**Comment by urielzen** [comment]
Awesome, I'll try this later tonight! Thanks

**Comment by urielzen** [comment]
Working great, thanks for your hard work
