### ISSUE TITLE
VScode === showing different space between lines

### ISSUE THREAD

**Issue by urielzen** [kiliman/operator-mono-lig#96]
**Operator Mono Lig Light**
In VSCode in Windows, the triple equal sign shows the two spaces between the lines one thicker than the other.

This happens with the default VSCode font size of 14. And default zoom.

![image](https://user-images.githubusercontent.com/7947179/62427292-9d3f8680-b6b6-11e9-9bae-f00c4d0f1e6c.png)

I have no scaling setup for my apps in Windows
![image](https://user-images.githubusercontent.com/7947179/62427329-2fe02580-b6b7-11e9-99e9-132bd19980c0.png)

**Comment by markypython** [comment]
What font variation are you using?  I.e. ssm book, ssm light, etc.

**Comment by dannymcgee** [comment]
This is a hinting issue. Buying a high-DPI monitor or adjusting the font size are the easiest ways to fix it. It's impossible to do the sort of granular hinting you would need to do to fix this dev-side without switching to TTF.

**Comment by kiliman** [comment]
Yes, it's difficult to get horizontal and vertical bars to be evenly space at small font sizes. Even with hinting, the rasterizer simply doesn't have enough pixels to align stuff. I find that 16+ font size gives enough pixels.

Plus the Mac uses anti-aliasing and not hinting to kind of smooth the edges. TrueType hinting may have better control, but unfortunately we're only supporting the OpenType font.

How does Fira Code look at the same font size?

**Comment by urielzen** [comment]
FiraCode has the same issue but only with Light

Fira Code Regular
![image](https://user-images.githubusercontent.com/7947179/62437650-bc1b3880-b709-11e9-868f-ad7594bfce2b.png)

Fira Code Medium
![image](https://user-images.githubusercontent.com/7947179/62437666-cccbae80-b709-11e9-98e8-829e04402199.png)

Fira Code Light
![image](https://user-images.githubusercontent.com/7947179/62437779-5da28a00-b70a-11e9-8992-4ab08d2a07e3.png)

**Comment by kiliman** [comment]
The light fonts are so thin, it is very noticeable when the bars are aligned perfectly. It's hard when you have to generate a line that is 1.2 pixels thick with a 2.1 pixel gap (just example numbers).

Anyway, I did rework that glyph in v2.2.2, so see if that makes any difference. Also, what happens when you bump the font size?

**Comment by urielzen** [comment]
with version 2.2.2 the bigger space moved to the bottom
![image](https://user-images.githubusercontent.com/7947179/62480968-d2131280-b776-11e9-86c4-6312c0c18684.png)

Making the font 15 size shows correctly, but it has obvious problem that there is less code in the screen.

Going all the way down to 12 also shows correctly, but it is just too small to read.

I cannot afford a high-DPI monitor so I'll just have to live with this one.

I understand this is a difficult issue to solve. You can go ahead and close it if you'd like. I just thought in bringing this up since it happens with the default font size in vscode, which I would think most people probably use.

Thanks
