### ISSUE TITLE
less_slash and slash_greater not aligned with others

### ISSUE THREAD

**Issue by urielzen** [kiliman/operator-mono-lig#97]
**Operator Mono Lig Light**
When using less_slash or slash_greater, the following characters are no longer aligned with regular characters.

VSCode Windows

![image](https://user-images.githubusercontent.com/7947179/62427399-286d4c00-b6b8-11e9-8c77-6a1a9504220e.png)

**Comment by dannymcgee** [comment]
By chance, did you use the regular version of Operator Mono Light, but rename the file to add 'SSm'? Just a guess, but I know the ScreenSmart fonts have slightly wider character widths and looser tracking than the print/designer fonts, which could cause a discrepancy like this if the calt glyphs are designed for the other version.

**Comment by markypython** [comment]
![2019-08-04_16-33-06](https://user-images.githubusercontent.com/25914066/62429548-8f4d2e00-b6d5-11e9-8d61-a5eaed78b165.png)

It shows up perfectly for me on Mac.

**Comment by kiliman** [comment]
Oops... looks like when the OM Light (non SSm) versions were being generated, the width was set to 625 (SSm width) vs 550 (Non-SSm width) for some of the glyphs. This is what is causing the alignment issues. I will fix these and push out a new build.

**Wrong width**
![image](https://user-images.githubusercontent.com/47168/62430284-6aae8180-b6e8-11e9-9637-440150e2f8f9.png)

**Correct width**
![image](https://user-images.githubusercontent.com/47168/62430297-96ca0280-b6e8-11e9-9f74-ceec967ea6b4.png)
