### ISSUE TITLE
Overlaping characters for SSm fonts

### ISSUE THREAD

**Issue by urielzen** [kiliman/operator-mono-lig#99]
None of the lig SSm fonts display correctly. The letters just overlap in the first character.

This is in a windows 10 OS. I thought at first this was an issue in my home PC, but the same thing happened in my work PC.

This is not an issue with VSCode only, I was able to reproduce in in MSWord.

Original
![image](https://user-images.githubusercontent.com/7947179/62481788-11426300-b779-11e9-8c19-cac208cf747d.png)

Lig version
![image](https://user-images.githubusercontent.com/7947179/62481837-2fa85e80-b779-11e9-9449-9d4e3d0e81c0.png)

**Comment by kiliman** [comment]
Did you build OM Light with the latest version v2.2.2?

**Comment by urielzen** [comment]
Yes, I had just pulled from master v 2.2.2, did npm install and build

**Comment by kiliman** [comment]
Ok, I will rebuild and reinstall the fonts to see if I see the same thing.

**Comment by kiliman** [comment]
I rebuilt the fonts and they all look fine. I believe your SSm version is not Operator Mono. NOTE that those characters are not fixed width. That looks like plain Operator (no Mono) which is a proportional font.

**Comment by urielzen** [comment]
You are right. Issue on my end. Closing this now
